{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "69dff3a3-a3aa-4325-80d6-514b89300655",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "================================================================================\n",
      "STEP 1: BLOG OUTLINE\n",
      "================================================================================\n",
      "1. Introduction to AI in Education\n",
      "2. Benefits of Artificial Intelligence in Learning\n",
      "3. Types of AI Applications in Education\n",
      "4. Challenges and Limitations of AI in Education\n",
      "5. The Future of AI in Education: Opportunities and Implications\n",
      "\n",
      "================================================================================\n",
      "STEP 3: INTRODUCTION & CONCLUSION\n",
      "================================================================================\n",
      "**Introduction**\n",
      "\n",
      "Artificial Intelligence (AI) is revolutionizing the education sector by providing personalized learning experiences, improving student outcomes, and enhancing the overall learning process. With the help of AI-powered tools, educators can now analyze student performance data, identify knowledge gaps, and develop targeted interventions to support struggling students. As AI technology continues to evolve, its potential to transform education is vast, and its impact will be felt in classrooms around the world.\n",
      "\n",
      "**Conclusion**\n",
      "\n",
      "As AI continues to play a significant role in shaping the future of education, educators, policymakers, and technologists must work together to ensure that the benefits of AI are equitably distributed and that its potential is harnessed to improve learning outcomes for all students. By embracing AI in education, we can create a more inclusive, effective, and student-centered learning environment that prepares students for success in an increasingly complex and interconnected world. Ultimately, the successful integration of AI in education will depend on our ability to navigate the challenges and opportunities that come with this transformative technology.\n",
      "\n",
      "================================================================================\n",
      "FULL BLOG GENERATED SUCCESSFULLY\n",
      "================================================================================\n",
      "\n",
      "Blog saved as: ai_education_blog.txt\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")\n",
    "topic = \"Artificial Intelligence in Education\"\n",
    "\n",
    "outline_prompt = f\"\"\"\n",
    "Generate a blog outline with exactly 5 headings\n",
    "for the topic:\n",
    "\n",
    "{topic}\n",
    "\n",
    "Only return the headings.\n",
    "\"\"\"\n",
    "\n",
    "response1 = client.chat.completions.create(\n",
    "\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "\n",
    "    messages=[\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": outline_prompt\n",
    "        }\n",
    "    ],\n",
    "\n",
    "    temperature=0.7\n",
    ")\n",
    "\n",
    "outline = response1.choices[0].message.content\n",
    "\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"STEP 1: BLOG OUTLINE\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(outline)\n",
    "\n",
    "headings = outline.split(\"\\n\")\n",
    "\n",
    "headings = [h.strip() for h in headings if h.strip()]\n",
    "\n",
    "blog_sections = []\n",
    "\n",
    "for heading in headings:\n",
    "\n",
    "    section_prompt = f\"\"\"\n",
    "Write 2 detailed paragraphs for the blog heading:\n",
    "\n",
    "{heading}\n",
    "\n",
    "Topic: {topic}\n",
    "\"\"\"\n",
    "\n",
    "    response2 = client.chat.completions.create(\n",
    "\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "\n",
    "        messages=[\n",
    "            {\n",
    "                \"role\": \"user\",\n",
    "                \"content\": section_prompt\n",
    "            }\n",
    "        ],\n",
    "\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    section_text = response2.choices[0].message.content\n",
    "\n",
    "    blog_sections.append(\n",
    "        {\n",
    "            \"heading\": heading,\n",
    "            \"content\": section_text\n",
    "        }\n",
    "    )\n",
    "\n",
    "intro_conclusion_prompt = f\"\"\"\n",
    "Write:\n",
    "\n",
    "1. A 3-sentence introduction\n",
    "2. A 3-sentence conclusion\n",
    "\n",
    "for a blog post on:\n",
    "\n",
    "{topic}\n",
    "\"\"\"\n",
    "\n",
    "response3 = client.chat.completions.create(\n",
    "\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "\n",
    "    messages=[\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": intro_conclusion_prompt\n",
    "        }\n",
    "    ],\n",
    "\n",
    "    temperature=0.7\n",
    ")\n",
    "\n",
    "intro_conclusion = response3.choices[0].message.content\n",
    "\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"STEP 3: INTRODUCTION & CONCLUSION\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(intro_conclusion)\n",
    "full_blog = \"\"\n",
    "\n",
    "full_blog += f\"BLOG TITLE: {topic}\\n\\n\"\n",
    "\n",
    "full_blog += intro_conclusion + \"\\n\\n\"\n",
    "\n",
    "for section in blog_sections:\n",
    "\n",
    "    full_blog += section[\"heading\"] + \"\\n\"\n",
    "    full_blog += \"-\" * len(section[\"heading\"]) + \"\\n\"\n",
    "\n",
    "    full_blog += section[\"content\"] + \"\\n\\n\"\n",
    "\n",
    "file_name = \"ai_education_blog.txt\"\n",
    "\n",
    "with open(file_name, \"w\", encoding=\"utf-8\") as file:\n",
    "\n",
    "    file.write(full_blog)\n",
    "\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"FULL BLOG GENERATED SUCCESSFULLY\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(f\"\\nBlog saved as: {file_name}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78a70510-20fd-4e1e-9217-1bd89a5e0f45",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
