{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "978d0e23-f5e3-410b-9bb6-faae79a9ef0e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "================================================================================\n",
      "STEP 1: BLOG OUTLINE\n",
      "================================================================================\n",
      "1. The Rise of AI in Education: Trends and Opportunities\n",
      "2. Enhancing Personalized Learning with AI-Powered Tools\n",
      "3. AI in Assessments and Grading: The Future of Evaluation\n",
      "4. Overcoming Challenges: Ethics and Bias in AI-Driven Education\n",
      "5. The Potential of AI in Transforming the Education System\n",
      "\n",
      "================================================================================\n",
      "STEP 3: INTRODUCTION & CONCLUSION\n",
      "================================================================================\n",
      "**Introduction**\n",
      "\n",
      "The integration of Artificial Intelligence (AI) in education has the potential to revolutionize the way we learn and teach. By leveraging AI-powered tools and technologies, educators can create personalized learning experiences that cater to the unique needs and abilities of each student, leading to improved academic outcomes and increased student engagement. As AI continues to evolve, it's essential to explore its applications and benefits in the education sector.\n",
      "\n",
      "**Conclusion**\n",
      "\n",
      "As we move forward in the era of AI-driven education, it's crucial to address the challenges and concerns surrounding its implementation, such as ensuring accessibility, equity, and teacher training. By harnessing the potential of AI in education, we can create a more inclusive and effective learning environment that prepares students for success in an increasingly complex and technological world. Ultimately, the future of education with AI has the potential to transform the way we learn, teach, and grow, and it's exciting to consider the possibilities that lie ahead.\n",
      "\n",
      "================================================================================\n",
      "FULL BLOG GENERATED SUCCESSFULLY\n",
      "================================================================================\n",
      "\n",
      "Blog saved as: ai_education_blog.txt\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")\n",
    "topic = \"Artificial Intelligence in Education\"\n",
    "outline_prompt = f\"\"\"\n",
    "Generate a blog outline with exactly 5 headings\n",
    "for the topic:\n",
    "\n",
    "{topic}\n",
    "\n",
    "Only return the headings.\n",
    "\"\"\"\n",
    "response1 = client.chat.completions.create(\n",
    "\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "\n",
    "    messages=[\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": outline_prompt\n",
    "        }\n",
    "    ],\n",
    "\n",
    "    temperature=0.7\n",
    ")\n",
    "outline = response1.choices[0].message.content\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"STEP 1: BLOG OUTLINE\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(outline)\n",
    "headings = outline.split(\"\\n\")\n",
    "headings = [h.strip() for h in headings if h.strip()]\n",
    "blog_sections = []\n",
    "\n",
    "for heading in headings:\n",
    "\n",
    "    section_prompt = f\"\"\"\n",
    "Write 2 detailed paragraphs for the blog heading:\n",
    "\n",
    "{heading}\n",
    "\n",
    "Topic: {topic}\n",
    "\"\"\"\n",
    "\n",
    "    response2 = client.chat.completions.create(\n",
    "\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "\n",
    "        messages=[\n",
    "            {\n",
    "                \"role\": \"user\",\n",
    "                \"content\": section_prompt\n",
    "            }\n",
    "        ],\n",
    "\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    section_text = response2.choices[0].message.content\n",
    "\n",
    "    blog_sections.append(\n",
    "        {\n",
    "            \"heading\": heading,\n",
    "            \"content\": section_text\n",
    "        }\n",
    "    )\n",
    "intro_conclusion_prompt = f\"\"\"\n",
    "Write:\n",
    "1. A 3-sentence introduction\n",
    "2. A 3-sentence conclusion\n",
    "for a blog post on:\n",
    "\n",
    "{topic}\n",
    "\"\"\"\n",
    "response3 = client.chat.completions.create(\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "    messages=[\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": intro_conclusion_prompt\n",
    "        }\n",
    "    ],\n",
    "    temperature=0.7\n",
    ")\n",
    "intro_conclusion = response3.choices[0].message.content\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"STEP 3: INTRODUCTION & CONCLUSION\")\n",
    "print(\"=\"*80)\n",
    "print(intro_conclusion)\n",
    "full_blog = \"\"\n",
    "full_blog += f\"BLOG TITLE: {topic}\\n\\n\"\n",
    "full_blog += intro_conclusion + \"\\n\\n\"\n",
    "for section in blog_sections:\n",
    "    full_blog += section[\"heading\"] + \"\\n\"\n",
    "    full_blog += \"-\" * len(section[\"heading\"]) + \"\\n\"\n",
    "    full_blog += section[\"content\"] + \"\\n\\n\"\n",
    "file_name = \"ai_education_blog.txt\"\n",
    "with open(file_name, \"w\", encoding=\"utf-8\") as file:\n",
    "    file.write(full_blog)\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"FULL BLOG GENERATED SUCCESSFULLY\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(f\"\\nBlog saved as: {file_name}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c810508-a25b-4ae3-9539-dda808190870",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
