{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0d60698-2b65-4763-b13b-a9fb850df897",
   "metadata": {},
   "outputs": [],
   "source": [
    "from groq import Groq\n",
    "client = Groq(\n",
    "    api_key=\"\"\n",
    ")\n",
    "\n",
    "python_code = \"\"\"\n",
    "def student_result(marks):\n",
    "\n",
    "    total = 0\n",
    "\n",
    "    for mark in marks:\n",
    "\n",
    "        total += mark\n",
    "\n",
    "    average = total / len(marks)\n",
    "\n",
    "    if average >= 90:\n",
    "        grade = \"A\"\n",
    "\n",
    "    elif average >= 75:\n",
    "        grade = \"B\"\n",
    "\n",
    "    elif average >= 50:\n",
    "        grade = \"C\"\n",
    "\n",
    "    else:\n",
    "        grade = \"Fail\"\n",
    "\n",
    "    print(\"Total Marks:\", total)\n",
    "    print(\"Average:\", average)\n",
    "    print(\"Grade:\", grade)\n",
    "\n",
    "    return grade\n",
    "\"\"\"\n",
    "\n",
    "zero_shot_prompt = f\"\"\"\n",
    "Review the following Python code and suggest improvements:\n",
    "\n",
    "{python_code}\n",
    "\"\"\"\n",
    "few_shot_prompt = f\"\"\"\n",
    "Example Code:\n",
    "def add(a,b):\n",
    " return a+b\n",
    "\n",
    "Example Review:\n",
    "1. Add proper spacing after commas.\n",
    "2. Use meaningful variable names.\n",
    "3. Add a docstring for clarity.\n",
    "\n",
    "Now review this Python code similarly:\n",
    "\n",
    "{python_code}\n",
    "\"\"\"\n",
    "cot_prompt = f\"\"\"\n",
    "Review the following Python code step by step.\n",
    "\n",
    "Step 1: Identify possible bugs.\n",
    "Step 2: Check coding style and readability.\n",
    "Step 3: Check security or robustness issues.\n",
    "Step 4: Suggest final improvements.\n",
    "\n",
    "Code:\n",
    "\n",
    "{python_code}\n",
    "\"\"\"\n",
    "\n",
    "def get_response(prompt):\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=[\n",
    "            {\n",
    "                \"role\": \"user\",\n",
    "                \"content\": prompt\n",
    "            }\n",
    "        ],\n",
    "        temperature=0.7\n",
    "    )\n",
    "\n",
    "    return response.choices[0].message.content\n",
    "\n",
    "print(\"\\n\" + \"=\"*70)\n",
    "print(\"ZERO-SHOT REVIEW\")\n",
    "print(\"=\"*70)\n",
    "zero_output = get_response(zero_shot_prompt)\n",
    "print(zero_output)\n",
    "print(\"\\n\" + \"=\"*70)\n",
    "print(\"FEW-SHOT REVIEW\")\n",
    "print(\"=\"*70)\n",
    "few_output = get_response(few_shot_prompt)\n",
    "print(few_output)\n",
    "print(\"\\n\" + \"=\"*70)\n",
    "print(\"CHAIN-OF-THOUGHT REVIEW\")\n",
    "print(\"=\"*70)\n",
    "cot_output = get_response(cot_prompt)\n",
    "print(cot_output)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
