{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7e5966ea-86f5-4703-b4c5-299e136ad96b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting langchain\n",
      "  Downloading langchain-1.3.2-py3-none-any.whl.metadata (5.8 kB)\n",
      "Collecting langchain-core\n",
      "  Downloading langchain_core-1.4.0-py3-none-any.whl.metadata (4.5 kB)\n",
      "Collecting langchain-groq\n",
      "  Downloading langchain_groq-1.1.2-py3-none-any.whl.metadata (2.4 kB)\n",
      "Collecting langgraph<1.3.0,>=1.2.2 (from langchain)\n",
      "  Downloading langgraph-1.2.2-py3-none-any.whl.metadata (8.0 kB)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core) (1.33)\n",
      "Collecting langchain-protocol>=0.0.14 (from langchain-core)\n",
      "  Downloading langchain_protocol-0.0.15-py3-none-any.whl.metadata (2.4 kB)\n",
      "Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core)\n",
      "  Downloading langsmith-0.8.5-py3-none-any.whl.metadata (15 kB)\n",
      "Requirement already satisfied: packaging>=23.2.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core) (25.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core) (6.0.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core) (9.1.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core) (4.15.0)\n",
      "Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core)\n",
      "  Downloading uuid_utils-0.16.0-cp313-cp313-win_amd64.whl.metadata (6.5 kB)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core) (3.0.0)\n",
      "Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph<1.3.0,>=1.2.2->langchain)\n",
      "  Downloading langgraph_checkpoint-4.1.1-py3-none-any.whl.metadata (5.2 kB)\n",
      "Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph<1.3.0,>=1.2.2->langchain)\n",
      "  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)\n",
      "Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.3.0,>=1.2.2->langchain)\n",
      "  Downloading langgraph_sdk-0.3.15-py3-none-any.whl.metadata (1.7 kB)\n",
      "Collecting xxhash>=3.5.0 (from langgraph<1.3.0,>=1.2.2->langchain)\n",
      "  Downloading xxhash-3.7.0-cp313-cp313-win_amd64.whl.metadata (13 kB)\n",
      "Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.2->langchain)\n",
      "  Downloading ormsgpack-1.12.2-cp313-cp313-win_amd64.whl.metadata (3.3 kB)\n",
      "Requirement already satisfied: httpx>=0.25.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.28.1)\n",
      "Collecting orjson>=3.11.5 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain)\n",
      "  Downloading orjson-3.11.9-cp313-cp313-win_amd64.whl.metadata (43 kB)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (2.32.5)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core) (0.24.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)\n",
      "Collecting groq<1.0.0,>=0.30.0 (from langchain-groq)\n",
      "  Downloading groq-0.37.1-py3-none-any.whl.metadata (16 kB)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)\n",
      "Requirement already satisfied: sniffio in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core) (2.5.0)\n",
      "Downloading langchain-1.3.2-py3-none-any.whl (121 kB)\n",
      "Downloading langchain_core-1.4.0-py3-none-any.whl (548 kB)\n",
      "   ---------------------------------------- 0.0/548.1 kB ? eta -:--:--\n",
      "   ---------------------------------------- 548.1/548.1 kB 3.1 MB/s  0:00:00\n",
      "Downloading langgraph-1.2.2-py3-none-any.whl (236 kB)\n",
      "Downloading langgraph_checkpoint-4.1.1-py3-none-any.whl (56 kB)\n",
      "Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)\n",
      "Downloading langgraph_sdk-0.3.15-py3-none-any.whl (98 kB)\n",
      "Downloading langsmith-0.8.5-py3-none-any.whl (399 kB)\n",
      "Downloading uuid_utils-0.16.0-cp313-cp313-win_amd64.whl (174 kB)\n",
      "Downloading langchain_groq-1.1.2-py3-none-any.whl (19 kB)\n",
      "Downloading groq-0.37.1-py3-none-any.whl (137 kB)\n",
      "Downloading langchain_protocol-0.0.15-py3-none-any.whl (7.0 kB)\n",
      "Downloading orjson-3.11.9-cp313-cp313-win_amd64.whl (127 kB)\n",
      "Downloading ormsgpack-1.12.2-cp313-cp313-win_amd64.whl (117 kB)\n",
      "Downloading xxhash-3.7.0-cp313-cp313-win_amd64.whl (31 kB)\n",
      "Installing collected packages: xxhash, uuid-utils, ormsgpack, orjson, langchain-protocol, langsmith, langgraph-sdk, groq, langchain-core, langgraph-checkpoint, langchain-groq, langgraph-prebuilt, langgraph, langchain\n",
      "\n",
      "   -------- -------------------------------  3/14 [orjson]\n",
      "   -------------- -------------------------  5/14 [langsmith]\n",
      "   -------------- -------------------------  5/14 [langsmith]\n",
      "   -------------- -------------------------  5/14 [langsmith]\n",
      "   -------------- -------------------------  5/14 [langsmith]\n",
      "   -------------- -------------------------  5/14 [langsmith]\n",
      "   -------------- -------------------------  5/14 [langsmith]\n",
      "   ----------------- ----------------------  6/14 [langgraph-sdk]\n",
      "   ----------------- ----------------------  6/14 [langgraph-sdk]\n",
      "  Attempting uninstall: groq\n",
      "   ----------------- ----------------------  6/14 [langgraph-sdk]\n",
      "    Found existing installation: groq 1.2.0\n",
      "   ----------------- ----------------------  6/14 [langgraph-sdk]\n",
      "    Uninstalling groq-1.2.0:\n",
      "   ----------------- ----------------------  6/14 [langgraph-sdk]\n",
      "      Successfully uninstalled groq-1.2.0\n",
      "   ----------------- ----------------------  6/14 [langgraph-sdk]\n",
      "   -------------------- -------------------  7/14 [groq]\n",
      "   -------------------- -------------------  7/14 [groq]\n",
      "   -------------------- -------------------  7/14 [groq]\n",
      "   -------------------- -------------------  7/14 [groq]\n",
      "   -------------------- -------------------  7/14 [groq]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ---------------------- -----------------  8/14 [langchain-core]\n",
      "   ------------------------- --------------  9/14 [langgraph-checkpoint]\n",
      "   ------------------------------- -------- 11/14 [langgraph-prebuilt]\n",
      "   ---------------------------------- ----- 12/14 [langgraph]\n",
      "   ---------------------------------- ----- 12/14 [langgraph]\n",
      "   ---------------------------------- ----- 12/14 [langgraph]\n",
      "   ---------------------------------- ----- 12/14 [langgraph]\n",
      "   ------------------------------------- -- 13/14 [langchain]\n",
      "   ------------------------------------- -- 13/14 [langchain]\n",
      "   ------------------------------------- -- 13/14 [langchain]\n",
      "   ---------------------------------------- 14/14 [langchain]\n",
      "\n",
      "Successfully installed groq-0.37.1 langchain-1.3.2 langchain-core-1.4.0 langchain-groq-1.1.2 langchain-protocol-0.0.15 langgraph-1.2.2 langgraph-checkpoint-4.1.1 langgraph-prebuilt-1.1.0 langgraph-sdk-0.3.15 langsmith-0.8.5 orjson-3.11.9 ormsgpack-1.12.2 uuid-utils-0.16.0 xxhash-3.7.0\n"
     ]
    }
   ],
   "source": [
    "!pip install langchain langchain-core langchain-groq"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "af38c11b-779e-4c01-aaf3-f89910f00ba8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==========================================================================================\n",
      "TEST CASE 1\n",
      "==========================================================================================\n",
      "**Python Lists**\n",
      "\n",
      "### What is a List?\n",
      "\n",
      "* A list is a collection of items that can be of any data type, including strings, integers, floats, and other lists.\n",
      "* Lists are denoted by square brackets `[]`.\n",
      "\n",
      "### Creating a List\n",
      "\n",
      "* `my_list = []` - an empty list\n",
      "* `my_list = [1, 2, 3, 4, 5]` - a list of integers\n",
      "* `my_list = [\"apple\", \"banana\", \"cherry\"]` - a list of strings\n",
      "* `my_list = [1, \"apple\", 3.14]` - a list of mixed data types\n",
      "\n",
      "### List Indexing\n",
      "\n",
      "* Accessing an element at a specific index: `my_list[index]`\n",
      "* Indexing starts at 0: `my_list[0]` is the first element\n",
      "* Negative indexing: `-1` accesses the last element, `-2` accesses the second last element, etc.\n",
      "\n",
      "### List Methods\n",
      "\n",
      "* `len(my_list)` - returns the number of elements in the list\n",
      "* `my_list.index(element)` - returns the index of the first occurrence of the element\n",
      "* `element in my_list` - checks if the element is in the list\n",
      "* `my_list.append(element)` - adds an element to the end of the list\n",
      "* `my_list.insert(index, element)` - adds an element at a specific index\n",
      "* `my_list.remove(element)` - removes the first occurrence of the element\n",
      "* `my_list.pop(index)` - removes and returns the element at the specified index\n",
      "\n",
      "### List Operations\n",
      "\n",
      "* `my_list + [1, 2, 3]` - concatenates two lists\n",
      "* `my_list * 2` - repeats the list\n",
      "* `my_list.sort()` - sorts the list in ascending order\n",
      "* `my_list.reverse()` - reverses the list\n",
      "\n",
      "### List Comprehensions\n",
      "\n",
      "* A concise way to create a new list from an existing list or other iterable.\n",
      "* `new_list = [expression for element in my_list]`\n",
      "* `new_list = [expression for element in my_list if condition]`\n",
      "\n",
      "### Example Use Cases\n",
      "\n",
      "* `fruits = [\"apple\", \"banana\", \"cherry\"]`\n",
      "* `fruits.sort()` - sorts the list in ascending order\n",
      "* `print(fruits)` - prints the sorted list\n",
      "* `new_fruits = [fruit.upper() for fruit in fruits]` - creates a new list with uppercase fruit names\n",
      "* `print(new_fruits)` - prints the new list\n",
      "\n",
      "==========================================================================================\n",
      "TEST CASE 2\n",
      "==========================================================================================\n",
      "As a Cybersecurity expert, I'd like to explain the topic of Phishing attacks in the following bullet points:\n",
      "\n",
      "**What is Phishing?**\n",
      "\n",
      "* Phishing is a type of social engineering attack where attackers attempt to trick victims into revealing sensitive information, such as passwords, credit card numbers, or personal data.\n",
      "* The term \"phishing\" comes from the word \"fishing,\" where attackers cast a net (in this case, an email or message) to catch unsuspecting victims.\n",
      "\n",
      "**Types of Phishing Attacks:**\n",
      "\n",
      "* **Email Phishing (Spear Phishing):** attackers send targeted emails that appear to come from a legitimate source, such as a bank or a friend.\n",
      "* **Spear Phishing:** a more targeted form of phishing, where attackers research their victims and send personalized emails.\n",
      "* **Whaling:** a type of spear phishing aimed at high-level executives or decision-makers.\n",
      "* **Smishing (SMS Phishing):** attackers send phishing messages via SMS or text messages.\n",
      "* **Vishing (Voice Phishing):** attackers use phone calls to trick victims into revealing sensitive information.\n",
      "* **Angler Phishing:** attackers use fake websites or apps to trick victims into revealing sensitive information.\n",
      "\n",
      "**Phishing Attack Methods:**\n",
      "\n",
      "* **Urgency and Scarcity:** attackers create a sense of urgency or scarcity to prompt victims into taking action quickly.\n",
      "* **Legitimacy:** attackers impersonate legitimate companies or organizations to gain trust.\n",
      "* **Personalization:** attackers use personal information to make their emails or messages appear more credible.\n",
      "* **Suspicious Links and Attachments:** attackers send links or attachments that, when clicked or opened, install malware or steal sensitive information.\n",
      "\n",
      "**Consequences of Phishing Attacks:**\n",
      "\n",
      "* **Data Breaches:** attackers can steal sensitive information, such as credit card numbers, social security numbers, or login credentials.\n",
      "* **Financial Losses:** attackers can use stolen information to make unauthorized transactions or purchases.\n",
      "* **Identity Theft:** attackers can use stolen information to impersonate victims and commit crimes.\n",
      "\n",
      "**Prevention and Mitigation:**\n",
      "\n",
      "* **Education and Awareness:** raise awareness about phishing attacks and their risks.\n",
      "* **Email Filters:** use email filters to block suspicious emails.\n",
      "* **Two-Factor Authentication:** use two-factor authentication to add an extra layer of security.\n",
      "* **Regular Security Updates:** keep software and systems up to date with the latest security patches.\n",
      "* **Regular Password Resets:** change passwords regularly to minimize the impact of a phishing attack.\n",
      "\n",
      "As a Cybersecurity expert, I hope this information helps you understand the risks and consequences of phishing attacks and how to prevent them.\n",
      "\n",
      "==========================================================================================\n",
      "TEST CASE 3\n",
      "==========================================================================================\n",
      "**Welcome to Machine Learning: A Beginner's Guide**\n",
      "\n",
      "As a data science mentor, I'm excited to introduce you to the fascinating world of machine learning. Machine learning is a subset of artificial intelligence (AI) that enables computers to learn from data and make predictions or decisions without being explicitly programmed.\n",
      "\n",
      "**What is Machine Learning?**\n",
      "\n",
      "Machine learning is a type of artificial intelligence that involves training algorithms on large datasets to make predictions, classify objects, or make decisions. The goal of machine learning is to enable computers to learn from experience and improve their performance over time.\n",
      "\n",
      "**Key Concepts:**\n",
      "\n",
      "1. **Data:** Machine learning algorithms require large amounts of data to learn from. This data can come from various sources, such as sensors, surveys, or existing databases.\n",
      "2. **Algorithms:** Machine learning algorithms are the backbone of machine learning. These algorithms take in data, process it, and generate predictions or decisions.\n",
      "3. **Training:** The process of feeding data to an algorithm and adjusting its parameters to improve its performance is called training.\n",
      "4. **Testing:** Once an algorithm is trained, it's tested on a separate dataset to evaluate its performance and accuracy.\n",
      "\n",
      "**Types of Machine Learning:**\n",
      "\n",
      "1. **Supervised Learning:** In this type of learning, the algorithm is trained on labeled data, where the correct output is already known. The algorithm learns to map inputs to outputs based on the labeled data.\n",
      "2. **Unsupervised Learning:** In this type of learning, the algorithm is trained on unlabeled data, and it must find patterns or structure in the data on its own.\n",
      "3. **Reinforcement Learning:** In this type of learning, the algorithm learns from rewards or penalties it receives for its actions.\n",
      "\n",
      "**Machine Learning Tasks:**\n",
      "\n",
      "1. **Classification:** Predicting a category or label for a given input (e.g., spam vs. non-spam emails).\n",
      "2. **Regression:** Predicting a continuous value for a given input (e.g., stock prices).\n",
      "3. **Clustering:** Grouping similar data points into clusters (e.g., customer segmentation).\n",
      "\n",
      "**Real-World Applications:**\n",
      "\n",
      "1. **Image Recognition:** Self-driving cars, facial recognition, and medical image analysis.\n",
      "2. **Natural Language Processing:** Chatbots, language translation, and sentiment analysis.\n",
      "3. **Recommendation Systems:** Personalized product recommendations on e-commerce websites.\n",
      "\n",
      "**Getting Started with Machine Learning:**\n",
      "\n",
      "1. **Choose a programming language:** Python is a popular choice for machine learning.\n",
      "2. **Select a library:** Scikit-learn, TensorFlow, or PyTorch are popular machine learning libraries.\n",
      "3. **Practice with datasets:** Start with simple datasets and gradually move to more complex ones.\n",
      "4. **Join online communities:** Participate in online forums, such as Kaggle or Reddit's machine learning community.\n",
      "\n",
      "I hope this introduction to machine learning has sparked your interest in this exciting field. As your data science mentor, I'm here to guide you through the journey of learning machine learning and applying it to real-world problems.\n",
      "\n",
      "==========================================================================================\n",
      "TEST CASE 4\n",
      "==========================================================================================\n",
      "**APIs: A Step-by-Step Guide**\n",
      "\n",
      "As a software engineer, APIs (Application Programming Interfaces) are an essential tool in software development. In this guide, we will explain what APIs are, their types, how they work, and provide a step-by-step example of creating and consuming an API.\n",
      "\n",
      "**Step 1: What is an API?**\n",
      "\n",
      "An API is a set of defined rules that enables different software systems to communicate with each other. It acts as an intermediary between a client (such as a web application or mobile app) and a server, allowing them to exchange data in a standardized format.\n",
      "\n",
      "**Step 2: Types of APIs**\n",
      "\n",
      "There are several types of APIs:\n",
      "\n",
      "1. **Web APIs**: Used for web-based applications, these APIs use HTTP requests and responses to exchange data.\n",
      "2. **Mobile APIs**: Used for mobile applications, these APIs use protocols such as REST (Representational State of Resource) or gRPC.\n",
      "3. **Microservices APIs**: Used for microservices architecture, these APIs enable communication between different services within an application.\n",
      "4. **GraphQL APIs**: Used for querying data, these APIs allow clients to specify exactly what data they need.\n",
      "\n",
      "**Step 3: How APIs Work**\n",
      "\n",
      "Here's a high-level overview of how APIs work:\n",
      "\n",
      "1. **Request**: A client sends a request to the API, specifying the action it wants to perform (e.g., retrieve data).\n",
      "2. **Authentication**: The API verifies the client's identity (if necessary) and grants access to the requested data.\n",
      "3. **Processing**: The API processes the request and retrieves the requested data from a database or other data source.\n",
      "4. **Response**: The API sends the response back to the client, usually in a JSON or XML format.\n",
      "\n",
      "**Step 4: Creating an API**\n",
      "\n",
      "Here's a step-by-step example of creating a simple API using Node.js and Express:\n",
      "\n",
      "**Step 4.1: Set up the project**\n",
      "\n",
      "Create a new project folder and initialize a new Node.js project using `npm init`.\n",
      "\n",
      "**Step 4.2: Install dependencies**\n",
      "\n",
      "Install Express.js using `npm install express`.\n",
      "\n",
      "**Step 4.3: Define the API endpoint**\n",
      "\n",
      "Create a new file called `app.js` and define a simple API endpoint that returns a list of users:\n",
      "```javascript\n",
      "const express = require('express');\n",
      "const app = express();\n",
      "\n",
      "app.get('/users', (req, res) => {\n",
      "  const users = [\n",
      "    { id: 1, name: 'John Doe' },\n",
      "    { id: 2, name: 'Jane Doe' },\n",
      "  ];\n",
      "  res.json(users);\n",
      "});\n",
      "\n",
      "app.listen(3000, () => {\n",
      "  console.log('Server listening on port 3000');\n",
      "});\n",
      "```\n",
      "**Step 4.4: Run the API**\n",
      "\n",
      "Run the API using `node app.js` and test it using a tool like Postman or cURL.\n",
      "\n",
      "**Step 5: Consuming an API**\n",
      "\n",
      "Here's a step-by-step example of consuming the API we created earlier using JavaScript and the Fetch API:\n",
      "\n",
      "**Step 5.1: Create a client**\n",
      "\n",
      "Create a new file called `client.js` and import the Fetch API:\n",
      "```javascript\n",
      "const fetch = require('node-fetch');\n",
      "```\n",
      "**Step 5.2: Send a request**\n",
      "\n",
      "Send a GET request to the API endpoint using the Fetch API:\n",
      "```javascript\n",
      "fetch('http://localhost:3000/users')\n",
      "  .then(response => response.json())\n",
      "  .then(data => console.log(data))\n",
      "  .catch(error => console.error(error));\n",
      "```\n",
      "**Step 5.3: Process the response**\n",
      "\n",
      "Process the response data in the callback function:\n",
      "```javascript\n",
      "fetch('http://localhost:3000/users')\n",
      "  .then(response => response.json())\n",
      "  .then(data => {\n",
      "    data.forEach(user => {\n",
      "      console.log(`User ${user.name} has ID ${user.id}`);\n",
      "    });\n",
      "  })\n",
      "  .catch(error => console.error(error));\n",
      "```\n",
      "This is a basic example of creating and consuming an API. In a real-world scenario, you would need to handle errors, implement security measures, and optimize performance.\n"
     ]
    }
   ],
   "source": [
    "from langchain_core.prompts import PromptTemplate\n",
    "from langchain_groq import ChatGroq\n",
    "from langchain_core.output_parsers import StrOutputParser\n",
    "llm = ChatGroq(\n",
    "    api_key=\"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\",\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "    temperature=0.7\n",
    ")\n",
    "\n",
    "prompt = PromptTemplate(\n",
    "\n",
    "    input_variables=[\"role\", \"topic\", \"format\"],\n",
    "\n",
    "    template=\"\"\"\n",
    "You are a {role}.\n",
    "\n",
    "Explain the topic:\n",
    "{topic}\n",
    "\n",
    "Output format:\n",
    "{format}\n",
    "\"\"\"\n",
    ")\n",
    "\n",
    "parser = StrOutputParser()\n",
    "\n",
    "chain = prompt | llm | parser\n",
    "\n",
    "test_inputs = [\n",
    "\n",
    "    {\n",
    "        \"role\": \"Python teacher\",\n",
    "        \"topic\": \"Python lists\",\n",
    "        \"format\": \"Short notes\"\n",
    "    },\n",
    "\n",
    "    {\n",
    "        \"role\": \"Cybersecurity expert\",\n",
    "        \"topic\": \"Phishing attacks\",\n",
    "        \"format\": \"Bullet points\"\n",
    "    },\n",
    "\n",
    "    {\n",
    "        \"role\": \"Data science mentor\",\n",
    "        \"topic\": \"Machine learning\",\n",
    "        \"format\": \"Beginner-friendly explanation\"\n",
    "    },\n",
    "\n",
    "    {\n",
    "        \"role\": \"Software engineer\",\n",
    "        \"topic\": \"APIs\",\n",
    "        \"format\": \"Step-by-step guide\"\n",
    "    }\n",
    "]\n",
    "\n",
    "for i, inputs in enumerate(test_inputs, start=1):\n",
    "\n",
    "    print(\"\\n\" + \"=\"*90)\n",
    "    print(f\"TEST CASE {i}\")\n",
    "    print(\"=\"*90)\n",
    "\n",
    "    output = chain.invoke(inputs)\n",
    "\n",
    "    print(output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb22fe48-893a-494f-88ae-32754d2a76a3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
