{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e0a05bf4-f198-47b0-9305-2ea9e328fdb6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==========================================================================================\n",
      "PROMPT\n",
      "==========================================================================================\n",
      "\n",
      "A farmer has 17 sheep.\n",
      "All but 9 die.\n",
      "\n",
      "How many sheep are left?\n",
      "Explain your reasoning carefully.\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "RUNNING MODEL: llama-3.1-8b-instant\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "MODEL OUTPUT:\n",
      "\n",
      "To find out how many sheep are left, we need to understand the given information.\n",
      "\n",
      "The farmer has 17 sheep initially. \n",
      "\n",
      "Then, it's stated that \"all but 9 die.\" This means that all the sheep, except for 9, died. \n",
      "\n",
      "So, we are looking for the number of sheep that are left (i.e., the 9 that didn't die).\n",
      "\n",
      "To find the answer, we don't need to subtract 9 from 17, as this would imply that 9 sheep died, leaving 8 sheep alive. However, the text explicitly states that \"all but 9 die,\" indicating that 9 sheep survived.\n",
      "\n",
      "Therefore, the answer is 9. There are 9 sheep left.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "RUNNING MODEL: llama-3.3-70b-versatile\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "MODEL OUTPUT:\n",
      "\n",
      "To find out how many sheep are left, we need to understand the phrase \"All but 9 die.\" This phrase means that 9 sheep will survive, and all the rest will die.\n",
      "\n",
      "Initially, the farmer has 17 sheep. If all but 9 die, that means 9 sheep will be left alive. \n",
      "\n",
      "So, the number of sheep that die is 17 (initial sheep) - 9 (sheep that survive) = 8 sheep.\n",
      "\n",
      "Therefore, the number of sheep left is 9.\n",
      "\n",
      "==========================================================================================\n",
      "MODEL COMPARISON TABLE\n",
      "==========================================================================================\n",
      "                  Model  Response Time (s)  Output Length\n",
      "   llama-3.1-8b-instant               0.76            565\n",
      "llama-3.3-70b-versatile               0.57            388\n",
      "\n",
      "==========================================================================================\n",
      "PROMPT\n",
      "==========================================================================================\n",
      "\n",
      "What is the capital of Japan?\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "RUNNING MODEL: llama-3.1-8b-instant\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "MODEL OUTPUT:\n",
      "\n",
      "The capital of Japan is Tokyo.\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "RUNNING MODEL: llama-3.3-70b-versatile\n",
      "--------------------------------------------------------------------------------\n",
      "\n",
      "MODEL OUTPUT:\n",
      "\n",
      "The capital of Japan is Tokyo.\n",
      "\n",
      "==========================================================================================\n",
      "MODEL COMPARISON TABLE\n",
      "==========================================================================================\n",
      "                  Model  Response Time (s)  Output Length\n",
      "   llama-3.1-8b-instant               0.12             30\n",
      "llama-3.3-70b-versatile               0.45             30\n",
      "\n",
      "==========================================================================================\n",
      "OBSERVATIONS\n",
      "==========================================================================================\n",
      "\n",
      "\n",
      "1. Smaller models are usually faster and cheaper.\n",
      "   They work well for simple factual questions.\n",
      "\n",
      "2. Larger models generally provide:\n",
      "   - better reasoning\n",
      "   - clearer explanations\n",
      "   - more detailed answers\n",
      "\n",
      "3. For simple tasks like:\n",
      "   - definitions\n",
      "   - factual lookups\n",
      "   - short answers\n",
      "\n",
      "   the smaller model is usually enough.\n",
      "\n",
      "4. For complex reasoning tasks,\n",
      "   coding help,\n",
      "   long explanations,\n",
      "   or nuanced understanding,\n",
      "\n",
      "   the larger model quality is often worth\n",
      "   the extra response time.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "import time\n",
    "import pandas as pd\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")\n",
    "def compare_models(prompt, models):\n",
    "\n",
    "    results = []\n",
    "\n",
    "    print(\"\\n\" + \"=\"*90)\n",
    "    print(\"PROMPT\")\n",
    "    print(\"=\"*90)\n",
    "\n",
    "    print(prompt)\n",
    "\n",
    "    for model_name in models:\n",
    "\n",
    "        print(\"\\n\" + \"-\"*80)\n",
    "        print(f\"RUNNING MODEL: {model_name}\")\n",
    "        print(\"-\"*80)\n",
    "        start_time = time.time()\n",
    "        response = client.chat.completions.create(\n",
    "\n",
    "            model=model_name,\n",
    "\n",
    "            messages=[\n",
    "                {\n",
    "                    \"role\": \"user\",\n",
    "                    \"content\": prompt\n",
    "                }\n",
    "            ],\n",
    "\n",
    "            temperature=0.7\n",
    "        )\n",
    "\n",
    "        end_time = time.time()\n",
    "        output = response.choices[0].message.content\n",
    "        response_time = round(end_time - start_time, 2)\n",
    "\n",
    "        output_length = len(output)\n",
    "\n",
    "        results.append({\n",
    "            \"Model\": model_name,\n",
    "            \"Response Time (s)\": response_time,\n",
    "            \"Output Length\": output_length\n",
    "        })\n",
    "        print(\"\\nMODEL OUTPUT:\\n\")\n",
    "        print(output)\n",
    "\n",
    "    df = pd.DataFrame(results)\n",
    "\n",
    "    print(\"\\n\" + \"=\"*90)\n",
    "    print(\"MODEL COMPARISON TABLE\")\n",
    "    print(\"=\"*90)\n",
    "\n",
    "    print(df.to_string(index=False))\n",
    "\n",
    "models = [\n",
    "\n",
    "    \"llama-3.1-8b-instant\",\n",
    "\n",
    "    \"llama-3.3-70b-versatile\"\n",
    "]\n",
    "\n",
    "complex_prompt = \"\"\"\n",
    "A farmer has 17 sheep.\n",
    "All but 9 die.\n",
    "\n",
    "How many sheep are left?\n",
    "Explain your reasoning carefully.\n",
    "\"\"\"\n",
    "\n",
    "compare_models(complex_prompt, models)\n",
    "\n",
    "simple_prompt = \"\"\"\n",
    "What is the capital of Japan?\n",
    "\"\"\"\n",
    "\n",
    "compare_models(simple_prompt, models)\n",
    "\n",
    "print(\"\\n\" + \"=\"*90)\n",
    "print(\"OBSERVATIONS\")\n",
    "print(\"=\"*90)\n",
    "\n",
    "print(\"\"\"\n",
    "\n",
    "1. Smaller models are usually faster and cheaper.\n",
    "   They work well for simple factual questions.\n",
    "\n",
    "2. Larger models generally provide:\n",
    "   - better reasoning\n",
    "   - clearer explanations\n",
    "   - more detailed answers\n",
    "\n",
    "3. For simple tasks like:\n",
    "   - definitions\n",
    "   - factual lookups\n",
    "   - short answers\n",
    "\n",
    "   the smaller model is usually enough.\n",
    "\n",
    "4. For complex reasoning tasks,\n",
    "   coding help,\n",
    "   long explanations,\n",
    "   or nuanced understanding,\n",
    "\n",
    "   the larger model quality is often worth\n",
    "   the extra response time.\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca8cff2a-73a7-4fec-b2f9-d308e12f64dd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
