{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "16b0e58c-b39d-4bba-9fda-5565bd379c0b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "af5b45a9de1942b2ae67bcb7a4c5e964",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Building index from PDF...\n",
      "Index saved!\n",
      "\n",
      "Chatbot Ready! Type 'exit' to stop\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "You:  exit\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import os\n",
    "import pickle\n",
    "\n",
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "from langchain_groq import ChatGroq\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "class PDFChatbotCLI:\n",
    "\n",
    "    def __init__(self, pdf_path):\n",
    "        self.pdf_path = pdf_path\n",
    "        self.index_file = pdf_path + \".pkl\"\n",
    "\n",
    "        self.history = []\n",
    "        self.last_sources = []\n",
    "\n",
    "        self.embedding_model = HuggingFaceEmbeddings(\n",
    "            model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
    "        )\n",
    "\n",
    "        self.llm = ChatGroq(\n",
    "            groq_api_key=\"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\",\n",
    "            model_name=\"llama-3.3-70b-versatile\"\n",
    "        )\n",
    "\n",
    "        self.load_or_build_index()\n",
    "\n",
    "    def build_index(self):\n",
    "\n",
    "        print(\"\\nBuilding index from PDF...\")\n",
    "\n",
    "        loader = PyPDFLoader(self.pdf_path)\n",
    "        docs = loader.load()\n",
    "\n",
    "        splitter = RecursiveCharacterTextSplitter(\n",
    "            chunk_size=500,\n",
    "            chunk_overlap=50\n",
    "        )\n",
    "\n",
    "        chunks = splitter.split_documents(docs)\n",
    "\n",
    "        self.texts = [c.page_content for c in chunks]\n",
    "        self.metadata = [c.metadata for c in chunks]\n",
    "\n",
    "        self.embeddings = np.array(\n",
    "            self.embedding_model.embed_documents(self.texts)\n",
    "        )\n",
    "\n",
    "        with open(self.index_file, \"wb\") as f:\n",
    "            pickle.dump((self.texts, self.metadata, self.embeddings), f)\n",
    "\n",
    "        print(\"Index saved!\")\n",
    "\n",
    "    def load_or_build_index(self):\n",
    "\n",
    "        if os.path.exists(self.index_file):\n",
    "\n",
    "            print(\"\\nLoading saved index...\")\n",
    "\n",
    "            with open(self.index_file, \"rb\") as f:\n",
    "                self.texts, self.metadata, self.embeddings = pickle.load(f)\n",
    "\n",
    "        else:\n",
    "            self.build_index()\n",
    "\n",
    "    def retrieve(self, query, k=3):\n",
    "\n",
    "        query_vec = self.embedding_model.embed_query(query)\n",
    "\n",
    "        scores = cosine_similarity([query_vec], self.embeddings)[0]\n",
    "\n",
    "        top_idx = np.argsort(scores)[::-1][:k]\n",
    "\n",
    "        results = []\n",
    "\n",
    "        for i in top_idx:\n",
    "            results.append({\n",
    "                \"text\": self.texts[i],\n",
    "                \"metadata\": self.metadata[i]\n",
    "            })\n",
    "\n",
    "        self.last_sources = results\n",
    "        return results\n",
    "\n",
    "    def show_sources(self):\n",
    "\n",
    "        print(\"\\n--- SOURCES ---\")\n",
    "\n",
    "        for i, s in enumerate(self.last_sources):\n",
    "\n",
    "            page = s[\"metadata\"].get(\"page\", \"Unknown\")\n",
    "            preview = s[\"text\"][:120].replace(\"\\n\", \" \")\n",
    "\n",
    "            print(f\"\\nSource {i+1}\")\n",
    "            print(\"Page:\", page)\n",
    "            print(\"Text:\", preview)\n",
    "\n",
    "    def summary(self):\n",
    "\n",
    "        convo = \"\\n\".join(\n",
    "            [f\"{r}: {m}\" for r, m in self.history]\n",
    "        )\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "Summarize in 3 bullet points:\n",
    "\n",
    "{convo}\n",
    "\"\"\"\n",
    "\n",
    "        res = self.llm.invoke(prompt)\n",
    "        return res.content\n",
    "\n",
    "    def ask(self, question):\n",
    "\n",
    "        if question.lower() == \"summary\":\n",
    "            result = self.summary()\n",
    "            print(\"\\nSUMMARY:\\n\", result)\n",
    "            return\n",
    "\n",
    "        if question.lower() == \"sources\":\n",
    "            self.show_sources()\n",
    "            return\n",
    "\n",
    "        docs = self.retrieve(question)\n",
    "\n",
    "        context = \"\\n\".join([d[\"text\"] for d in docs])\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "Answer using only context.\n",
    "\n",
    "Context:\n",
    "{context}\n",
    "\n",
    "Question: {question}\n",
    "\"\"\"\n",
    "\n",
    "        response = self.llm.invoke(prompt).content\n",
    "\n",
    "        self.history.append((\"user\", question))\n",
    "        self.history.append((\"bot\", response))\n",
    "\n",
    "        print(\"\\nBOT:\", response)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\n",
    "    if len(sys.argv) < 2:\n",
    "        print(\"Usage: python pdf_rag_chatbot_cli.py <pdf_file>\")\n",
    "        sys.exit()\n",
    "\n",
    "    pdf_path = sys.argv[1]\n",
    "\n",
    "    chatbot = PDFChatbotCLI(r\"C:\\Users\\amrit\\Downloads\\survey cdc.pdf\")\n",
    "\n",
    "    print(\"\\nChatbot Ready! Type 'exit' to stop\")\n",
    "\n",
    "    while True:\n",
    "\n",
    "        user_input = input(\"\\nYou: \")\n",
    "\n",
    "        if user_input.lower() == \"exit\":\n",
    "            break\n",
    "\n",
    "        chatbot.ask(user_input)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3c4883f2-3305-4eac-9de9-3f79a6b05230",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
