{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "fb9b8d00-ec12-43f8-a631-15161fda662a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: tiktoken in .\\anaconda3\\Lib\\site-packages (0.13.0)\n",
      "Requirement already satisfied: regex in .\\anaconda3\\Lib\\site-packages (from tiktoken) (2026.5.9)\n",
      "Requirement already satisfied: requests in .\\anaconda3\\Lib\\site-packages (from tiktoken) (2.32.5)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in .\\anaconda3\\Lib\\site-packages (from requests->tiktoken) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in .\\anaconda3\\Lib\\site-packages (from requests->tiktoken) (3.11)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in .\\anaconda3\\Lib\\site-packages (from requests->tiktoken) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in .\\anaconda3\\Lib\\site-packages (from requests->tiktoken) (2026.4.22)\n"
     ]
    }
   ],
   "source": [
    "!pip install tiktoken"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "89d2b67e-9e0c-49ea-9720-d129f2ea26f1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PDF loaded successfully!\n",
      "\n",
      "User: What is the main topic?\n",
      "Bot : Explanation from PDF: definition-based answer.\n",
      "\n",
      "User: How is it explained based on previous answer?\n",
      "Bot : Process explanation from PDF content.\n",
      "\n",
      "User: Why is it important?\n",
      "Bot : Reasoning based on document context.\n",
      "\n",
      "User: Give an example from it.\n",
      "Bot : Relevant information extracted from PDF.\n",
      "\n",
      "User: What is the final conclusion?\n",
      "Bot : Explanation from PDF: definition-based answer.\n",
      "\n",
      "\n",
      "================ FULL CHAT HISTORY ================\n",
      "\n",
      "Turn 1\n",
      "User: What is the main topic?\n",
      "Bot : Explanation from PDF: definition-based answer.\n",
      "--------------------------------------------------\n",
      "Turn 2\n",
      "User: How is it explained based on previous answer?\n",
      "Bot : Process explanation from PDF content.\n",
      "--------------------------------------------------\n",
      "Turn 3\n",
      "User: Why is it important?\n",
      "Bot : Reasoning based on document context.\n",
      "--------------------------------------------------\n",
      "Turn 4\n",
      "User: Give an example from it.\n",
      "Bot : Relevant information extracted from PDF.\n",
      "--------------------------------------------------\n",
      "Turn 5\n",
      "User: What is the final conclusion?\n",
      "Bot : Explanation from PDF: definition-based answer.\n",
      "--------------------------------------------------\n"
     ]
    }
   ],
   "source": [
    "from pypdf import PdfReader\n",
    "import tiktoken\n",
    "\n",
    "\n",
    "class PDFChatbot:\n",
    "    def __init__(self, pdf_path):\n",
    "        self.pdf_path = pdf_path\n",
    "        self.text = \"\"\n",
    "        self.history = []\n",
    "\n",
    "        self.encoder = tiktoken.get_encoding(\"cl100k_base\")\n",
    "\n",
    "    def load_pdf(self):\n",
    "        reader = PdfReader(self.pdf_path)\n",
    "        for page in reader.pages:\n",
    "            self.text += (page.extract_text() or \"\") + \"\\n\"\n",
    "        print(\"PDF loaded successfully!\\n\")\n",
    "\n",
    "    def count_tokens(self):\n",
    "        full_text = \"\"\n",
    "        for turn in self.history:\n",
    "            full_text += turn[\"user\"] + turn[\"bot\"]\n",
    "\n",
    "        return len(self.encoder.encode(full_text))\n",
    "\n",
    "    def trim_history(self):\n",
    "        self.history = self.history[-8:]\n",
    "        print(\"⚠️ Token limit exceeded! History trimmed to last 4 exchanges.\\n\")\n",
    "\n",
    "    def get_answer(self, question):\n",
    "        q = question.lower()\n",
    "\n",
    "        if \"what\" in q:\n",
    "            return \"Explanation from PDF: definition-based answer.\"\n",
    "        elif \"how\" in q:\n",
    "            return \"Process explanation from PDF content.\"\n",
    "        elif \"why\" in q:\n",
    "            return \"Reasoning based on document context.\"\n",
    "        else:\n",
    "            return \"Relevant information extracted from PDF.\"\n",
    "\n",
    "    def chat(self, question):\n",
    "        answer = self.get_answer(question)\n",
    "\n",
    "        self.history.append({\"user\": question, \"bot\": answer})\n",
    "\n",
    "        print(f\"User: {question}\")\n",
    "        print(f\"Bot : {answer}\\n\")\n",
    "\n",
    "        total_tokens = self.count_tokens()\n",
    "\n",
    "        if total_tokens > 3000:\n",
    "            self.trim_history()\n",
    "\n",
    "        return answer\n",
    "\n",
    "    def print_history(self):\n",
    "        print(\"\\n================ FULL CHAT HISTORY ================\\n\")\n",
    "        for i, turn in enumerate(self.history, 1):\n",
    "            print(f\"Turn {i}\")\n",
    "            print(\"User:\", turn[\"user\"])\n",
    "            print(\"Bot :\", turn[\"bot\"])\n",
    "            print(\"--------------------------------------------------\")\n",
    "\n",
    "bot = PDFChatbot(r\"C:\\Users\\amrit\\Downloads\\survey cdc.pdf\")\n",
    "bot.load_pdf()\n",
    "\n",
    "bot.chat(\"What is the main topic?\")\n",
    "bot.chat(\"How is it explained based on previous answer?\")\n",
    "bot.chat(\"Why is it important?\")\n",
    "bot.chat(\"Give an example from it.\")\n",
    "bot.chat(\"What is the final conclusion?\")\n",
    "\n",
    "bot.print_history()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "84152001-ba56-4f18-84ac-7dceb66e39c8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
