{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dcfc20b1-a4e3-4624-8e91-dcc4b445f784",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain-text-splitters in c:\\users\\amrit\\anaconda3\\lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-text-splitters) (1.4.0)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.0.15)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.8.5)\n",
      "Requirement already satisfied: packaging>=23.2.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (25.0)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.12.4)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (6.0.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (9.1.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.0.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.9.14 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.32.5)\n",
      "Requirement already satisfied: xxhash>=3.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.7.0)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.24.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.4.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.5.0)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.3.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install langchain-text-splitters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a4d5757b-6a85-46c5-a10a-be269e15843e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting langchain-huggingface\n",
      "  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)\n",
      "Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-huggingface) (1.16.4)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-huggingface) (1.4.0)\n",
      "Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-huggingface) (0.22.2)\n",
      "Requirement already satisfied: click>=8.4.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.1)\n",
      "Requirement already satisfied: filelock>=3.10.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.20.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.10.0)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.28.1)\n",
      "Requirement already satisfied: packaging>=20.9 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (25.0)\n",
      "Requirement already satisfied: pyyaml>=5.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (6.0.3)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.1)\n",
      "Requirement already satisfied: typer<0.26.0,>=0.20.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.20.0)\n",
      "Requirement already satisfied: typing-extensions>=4.1.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.15.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.16.0)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.0.15)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.8.5)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.12.4)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (9.1.2)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.0.0)\n",
      "Requirement already satisfied: orjson>=3.9.14 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.32.5)\n",
      "Requirement already satisfied: xxhash>=3.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.7.0)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.24.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.4.2)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.4)\n",
      "Requirement already satisfied: rich>=10.11.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (14.2.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from click>=8.4.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.4.6)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.5.0)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.19.2)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.1.2)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.3.0)\n",
      "Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)\n",
      "Installing collected packages: langchain-huggingface\n",
      "Successfully installed langchain-huggingface-1.2.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install langchain-huggingface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a34054aa-12b1-4ad3-b353-b9db25aaa133",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain in c:\\users\\amrit\\anaconda3\\lib\\site-packages (1.3.2)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain) (1.4.0)\n",
      "Requirement already satisfied: langgraph<1.3.0,>=1.2.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain) (1.2.2)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.0.15)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.8.5)\n",
      "Requirement already satisfied: packaging>=23.2.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (25.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (6.0.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (9.1.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (3.0.0)\n",
      "Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (4.1.1)\n",
      "Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (1.1.0)\n",
      "Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (0.3.15)\n",
      "Requirement already satisfied: xxhash>=3.5.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (3.7.0)\n",
      "Requirement already satisfied: ormsgpack>=1.12.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.2->langchain) (1.12.2)\n",
      "Requirement already satisfied: httpx>=0.25.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.11.5 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.32.5)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (0.24.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.5.0)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.3.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install -U langchain"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "b89e149d-4dda-4606-b88b-e9b925cc7d24",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found existing installation: langchain 1.3.2\n",
      "Uninstalling langchain-1.3.2:\n",
      "  Successfully uninstalled langchain-1.3.2\n",
      "Found existing installation: langchain-core 1.4.0\n",
      "Uninstalling langchain-core-1.4.0:\n",
      "  Successfully uninstalled langchain-core-1.4.0\n",
      "Found existing installation: langchain-community 0.4.2\n",
      "Uninstalling langchain-community-0.4.2:\n",
      "  Successfully uninstalled langchain-community-0.4.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip uninstall langchain langchain-core langchain-community -y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "38fe7de4-454e-4ee0-8a04-2e518c155dba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in c:\\users\\amrit\\anaconda3\\lib\\site-packages (25.3)\n",
      "Collecting pip\n",
      "  Using cached pip-26.1.1-py3-none-any.whl.metadata (4.6 kB)\n",
      "Using cached pip-26.1.1-py3-none-any.whl (1.8 MB)\n",
      "Installing collected packages: pip\n",
      "  Attempting uninstall: pip\n",
      "    Found existing installation: pip 25.3\n",
      "    Uninstalling pip-25.3:\n",
      "      Successfully uninstalled pip-25.3\n",
      "Successfully installed pip-26.1.1\n"
     ]
    }
   ],
   "source": [
    "!python -m pip install --upgrade pip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "fa5784e4-5320-4594-a83d-8f8fcf3a025b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting langchain-community\n",
      "  Using cached langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (3.13.2)\n",
      "Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (0.4.3)\n",
      "Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (1.0.7)\n",
      "Collecting langchain-core<2.0.0,>=1.4.0 (from langchain-community)\n",
      "  Using cached langchain_core-1.4.0-py3-none-any.whl.metadata (4.5 kB)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (0.8.5)\n",
      "Requirement already satisfied: numpy>=2.1.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.3.5)\n",
      "Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.12.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (6.0.3)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.32.5 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.32.5)\n",
      "Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.0.43)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (9.1.2)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)\n",
      "Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in .\\anaconda3\\Lib\\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in .\\anaconda3\\Lib\\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.0.15)\n",
      "Requirement already satisfied: packaging>=23.2.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (25.0)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in .\\anaconda3\\Lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-community) (3.0.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.9.14 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)\n",
      "Requirement already satisfied: xxhash>=3.0.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.7.0)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.24.0)\n",
      "Requirement already satisfied: anyio in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.10.0)\n",
      "Requirement already satisfied: certifi in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)\n",
      "Requirement already satisfied: idna in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in .\\anaconda3\\Lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.4.2)\n",
      "Requirement already satisfied: python-dotenv>=0.21.0 in .\\anaconda3\\Lib\\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)\n",
      "Requirement already satisfied: greenlet>=1 in .\\anaconda3\\Lib\\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.2.4)\n",
      "Requirement already satisfied: sniffio>=1.1 in .\\anaconda3\\Lib\\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.0)\n",
      "Using cached langchain_community-0.4.2-py3-none-any.whl (2.4 MB)\n",
      "Using cached langchain_core-1.4.0-py3-none-any.whl (548 kB)\n",
      "Installing collected packages: langchain-core, langchain-community\n",
      "\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   ---------------------------------------- 0/2 [langchain-core]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   -------------------- ------------------- 1/2 [langchain-community]\n",
      "   ---------------------------------------- 2/2 [langchain-community]\n",
      "\n",
      "Successfully installed langchain-community-0.4.2 langchain-core-1.4.0\n"
     ]
    }
   ],
   "source": [
    "!pip install langchain-community --default-timeout=100"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "593f51cb-605a-4066-9cf1-407b229a4381",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Embeddings Import Successful\n"
     ]
    }
   ],
   "source": [
    "from langchain_community.embeddings import HuggingFaceEmbeddings\n",
    "\n",
    "print(\"Embeddings Import Successful\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "dc6b3d53-6e74-4845-8230-5552e815cb80",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Pages Loaded: 15\n",
      "Chunks Created: 53\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f20ef681ae0e4829aac7611b2b8453a9",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "Question: What is the main topic of the PDF?\n",
      "------------------------------------------------------------\n",
      "Answer:\n",
      "The main topic of the text appears to be related to a survey about stress and coping mechanisms among students, specifically focusing on academic and student-related matters.\n",
      "============================================================\n",
      "\n",
      "============================================================\n",
      "Question: Summarize the document.\n",
      "------------------------------------------------------------\n",
      "Answer:\n",
      "The document reports on the emotional state of respondents in daily life. Overall, respondents experience moderate to above-average happiness, indicating they have emotional or social support available. However, a significant proportion of respondents (45%) reported feeling stressed \"sometimes\", with 29% feeling stressed \"often\" and 12% feeling stressed \"always\". This suggests that while respondents generally feel supported and happy, stress is still a common experience for many of them.\n",
      "============================================================\n",
      "\n",
      "============================================================\n",
      "Question: What are the important concepts?\n",
      "------------------------------------------------------------\n",
      "Answer:\n",
      "The important concepts in the given context are:\n",
      "\n",
      "1. **Happiness**: Measuring the level of happiness in daily life, specifically on a scale of 1-10.\n",
      "2. **Emotional Well-being**: Assessing the emotional state of the survey respondents.\n",
      "3. **Life Satisfaction**: Evaluating the respondents' satisfaction with their life.\n",
      "4. **Personal Information**: Collecting demographic data, including:\n",
      "\t* **Age group**\n",
      "\t* **Gender**\n",
      "\t* **Educational level**\n",
      "\t* **Current status** (student, employed, self-employed, or unemployed)\n",
      "5. **Student community**: The survey is largely centered on the student community, focusing on academic and student-related matters.\n",
      "============================================================\n",
      "\n",
      "============================================================\n",
      "Question: Explain one key idea.\n",
      "------------------------------------------------------------\n",
      "Answer:\n",
      "One key idea from the given context is that the respondents' overall happiness in daily life is moderate to above-average, despite some individuals expressing dissatisfaction, as indicated by the \"Very dissatisfied\" option.\n",
      "============================================================\n",
      "\n",
      "============================================================\n",
      "Question: What conclusion is given?\n",
      "------------------------------------------------------------\n",
      "Answer:\n",
      "The conclusion given is that respondents experience moderate to above-average happiness in daily life.\n",
      "============================================================\n"
     ]
    }
   ],
   "source": [
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "from langchain_community.embeddings import HuggingFaceEmbeddings\n",
    "from langchain_community.vectorstores import FAISS\n",
    "from langchain_groq import ChatGroq\n",
    "\n",
    "import os\n",
    "\n",
    "pdf_path = r\"C:\\Users\\amrit\\Downloads\\survey cdc.pdf\"\n",
    "\n",
    "loader = PyPDFLoader(pdf_path)\n",
    "\n",
    "documents = loader.load()\n",
    "\n",
    "print(\"Pages Loaded:\", len(documents))\n",
    "\n",
    "text_splitter = RecursiveCharacterTextSplitter(\n",
    "    chunk_size=500,\n",
    "    chunk_overlap=50\n",
    ")\n",
    "\n",
    "docs = text_splitter.split_documents(documents)\n",
    "\n",
    "print(\"Chunks Created:\", len(docs))\n",
    "\n",
    "embeddings = HuggingFaceEmbeddings(\n",
    "    model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
    ")\n",
    "\n",
    "vectorstore = FAISS.from_documents(docs, embeddings)\n",
    "\n",
    "retriever = vectorstore.as_retriever(search_kwargs={\"k\": 3})\n",
    "\n",
    "os.environ[\"GROQ_API_KEY\"] = \"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\"\n",
    "\n",
    "llm = ChatGroq(\n",
    "    model_name=\"llama-3.3-70b-versatile\"\n",
    ")\n",
    "questions = [\n",
    "    \"What is the main topic of the PDF?\",\n",
    "    \"Summarize the document.\",\n",
    "    \"What are the important concepts?\",\n",
    "    \"Explain one key idea.\",\n",
    "    \"What conclusion is given?\"\n",
    "]\n",
    "\n",
    "for q in questions:\n",
    "\n",
    "    docs = retriever.invoke(q)\n",
    "\n",
    "    context = \"\\n\".join([doc.page_content for doc in docs])\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "    Answer the question using the context below.\n",
    "\n",
    "    Context:\n",
    "    {context}\n",
    "\n",
    "    Question:\n",
    "    {q}\n",
    "    \"\"\"\n",
    "\n",
    "    response = llm.invoke(prompt)\n",
    "\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(\"Question:\", q)\n",
    "    print(\"-\"*60)\n",
    "    print(\"Answer:\")\n",
    "    print(response.content)\n",
    "    print(\"=\"*60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "697c2c75-a4a7-48cb-8e71-3d66ac10662b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
