{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "e8e892dd-a8d1-4b1f-a5a7-5ab8a31e1f4a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain-community in .\\anaconda3\\Lib\\site-packages (0.4.2)\n",
      "Requirement already satisfied: langchain-text-splitters in .\\anaconda3\\Lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-groq in .\\anaconda3\\Lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-huggingface in .\\anaconda3\\Lib\\site-packages (1.2.2)\n",
      "Requirement already satisfied: sentence-transformers in .\\anaconda3\\Lib\\site-packages (5.5.1)\n",
      "Requirement already satisfied: pypdf in .\\anaconda3\\Lib\\site-packages (6.12.2)\n",
      "Requirement already satisfied: scikit-learn in .\\anaconda3\\Lib\\site-packages (1.7.2)\n",
      "Requirement already satisfied: tiktoken in .\\anaconda3\\Lib\\site-packages (0.13.0)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (3.13.2)\n",
      "Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (0.4.3)\n",
      "Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (1.0.7)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (1.4.0)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (0.8.6)\n",
      "Requirement already satisfied: numpy>=2.1.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.3.5)\n",
      "Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.12.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (6.0.3)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.32.5 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.32.5)\n",
      "Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.0.43)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (8.5.0)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in .\\anaconda3\\Lib\\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.0.15)\n",
      "Requirement already satisfied: packaging>=23.2.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (24.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in .\\anaconda3\\Lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-community) (3.0.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.9.14 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)\n",
      "Requirement already satisfied: websockets>=15.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (16.0)\n",
      "Requirement already satisfied: xxhash>=3.0.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.7.0)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.24.0)\n",
      "Requirement already satisfied: anyio in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.10.0)\n",
      "Requirement already satisfied: certifi in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)\n",
      "Requirement already satisfied: idna in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in .\\anaconda3\\Lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.4.2)\n",
      "Requirement already satisfied: python-dotenv>=0.21.0 in .\\anaconda3\\Lib\\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)\n",
      "Requirement already satisfied: greenlet>=1 in .\\anaconda3\\Lib\\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.2.4)\n",
      "Requirement already satisfied: groq<1.0.0,>=0.30.0 in .\\anaconda3\\Lib\\site-packages (from langchain-groq) (0.37.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in .\\anaconda3\\Lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)\n",
      "Requirement already satisfied: sniffio in .\\anaconda3\\Lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.0)\n",
      "Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in .\\anaconda3\\Lib\\site-packages (from langchain-huggingface) (1.16.4)\n",
      "Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in .\\anaconda3\\Lib\\site-packages (from langchain-huggingface) (0.22.2)\n",
      "Requirement already satisfied: click>=8.4.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.1)\n",
      "Requirement already satisfied: filelock>=3.10.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.20.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.10.0)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.1)\n",
      "Requirement already satisfied: typer<0.26.0,>=0.20.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.20.0)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in .\\anaconda3\\Lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.4)\n",
      "Requirement already satisfied: rich>=10.11.0 in .\\anaconda3\\Lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (14.2.0)\n",
      "Requirement already satisfied: transformers<6.0.0,>=4.41.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (5.9.0)\n",
      "Requirement already satisfied: torch>=1.11.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (2.12.0)\n",
      "Requirement already satisfied: scipy>=1.0.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (1.16.3)\n",
      "Requirement already satisfied: regex>=2025.10.22 in .\\anaconda3\\Lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in .\\anaconda3\\Lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in .\\anaconda3\\Lib\\site-packages (from scikit-learn) (1.5.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in .\\anaconda3\\Lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: colorama in .\\anaconda3\\Lib\\site-packages (from click>=8.4.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.4.6)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in .\\anaconda3\\Lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\\anaconda3\\Lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.19.2)\n",
      "Requirement already satisfied: mdurl~=0.1 in .\\anaconda3\\Lib\\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.1.2)\n",
      "Requirement already satisfied: setuptools<82 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)\n",
      "Requirement already satisfied: sympy>=1.13.3 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)\n",
      "Requirement already satisfied: networkx>=2.5.1 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.5)\n",
      "Requirement already satisfied: jinja2 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\\anaconda3\\Lib\\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in .\\anaconda3\\Lib\\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "3a52a6b7d4a841d38023a06158060105",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "TURN 1\n",
      "\n",
      "USER:\n",
      "What is the main topic of the PDF?\n",
      "\n",
      "Current History Tokens: 44\n",
      "\n",
      "BOT:\n",
      "The main topic of the PDF appears to be academic and student-related matters, with a focus on the student community, specifically regarding stress and handling difficult situations.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 2\n",
      "\n",
      "USER:\n",
      "Explain the topic simply.\n",
      "\n",
      "Current History Tokens: 86\n",
      "\n",
      "BOT:\n",
      "The topic is about students and how they feel, especially about their happiness and well-being. It's based on a survey that mostly includes students' thoughts and experiences.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 3\n",
      "\n",
      "USER:\n",
      "summary\n",
      "\n",
      "SUMMARY\n",
      "* The main topic of the PDF is related to academic and student matters, focusing on the student community.\n",
      "* The topic specifically addresses issues of stress and handling difficult situations that students may face.\n",
      "* The PDF discusses students' happiness and well-being, based on a survey that includes their thoughts and experiences.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 4\n",
      "\n",
      "USER:\n",
      "Which libraries are mentioned?\n",
      "\n",
      "Current History Tokens: 136\n",
      "\n",
      "BOT:\n",
      "There are no libraries mentioned in the context provided. The context appears to be focused on a survey related to student happiness, life satisfaction, and emotional well-being, but it does not mention any specific libraries.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 5\n",
      "\n",
      "USER:\n",
      "sources\n",
      "\n",
      "LAST RETRIEVED SOURCES\n",
      "\n",
      "Source 1\n",
      "Page: 3\n",
      "Preview: t o  a c a d e m i c  a n d  s t u d e n t -  r e l a t e d  m a t t e r s .  O v e r a l l ,  t h e...\n",
      "\n",
      "Source 2\n",
      "Page: 11\n",
      "Preview: S u r v e y  Q u e s t i o n n a i r e :  H a p p i n e s s  a n d  L i f e  S a t i s f a c t i o n...\n",
      "\n",
      "Source 3\n",
      "Page: 11\n",
      "Preview: S ection B: Happiness & Emotional Well-being  5. On a scale of 1–10, how happy do you feel in your d...\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 6\n",
      "\n",
      "USER:\n",
      "How are those libraries used?\n",
      "\n",
      "Current History Tokens: 209\n",
      "\n",
      "BOT:\n",
      "As I mentioned earlier, there are no libraries mentioned in the context provided. The context appears to be focused on a survey related to student happiness, life satisfaction, and emotional well-being, but it does not mention any specific libraries. Therefore, I don't have any information on how libraries are used in this context.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "FINAL MESSAGE HISTORY\n",
      "\n",
      "USER:\n",
      "What is the main topic of the PDF?\n",
      "\n",
      "ASSISTANT:\n",
      "The main topic of the PDF appears to be academic and student-related matters, with a focus on the student community, specifically regarding stress and handling difficult situations.\n",
      "\n",
      "USER:\n",
      "Explain the topic simply.\n",
      "\n",
      "ASSISTANT:\n",
      "The topic is about students and how they feel, especially about their happiness and well-being. It's based on a survey that mostly includes students' thoughts and experiences.\n",
      "\n",
      "USER:\n",
      "Which libraries are mentioned?\n",
      "\n",
      "ASSISTANT:\n",
      "There are no libraries mentioned in the context provided. The context appears to be focused on a survey related to student happiness, life satisfaction, and emotional well-being, but it does not mention any specific libraries.\n",
      "\n",
      "USER:\n",
      "How are those libraries used?\n",
      "\n",
      "ASSISTANT:\n",
      "As I mentioned earlier, there are no libraries mentioned in the context provided. The context appears to be focused on a survey related to student happiness, life satisfaction, and emotional well-being, but it does not mention any specific libraries. Therefore, I don't have any information on how libraries are used in this context.\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "!{sys.executable} -m pip install \\\n",
    "langchain-community \\\n",
    "langchain-text-splitters \\\n",
    "langchain-groq \\\n",
    "langchain-huggingface \\\n",
    "sentence-transformers \\\n",
    "pypdf \\\n",
    "scikit-learn \\\n",
    "tiktoken\n",
    "\n",
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "from langchain_groq import ChatGroq\n",
    "\n",
    "import numpy as np\n",
    "\n",
    "import tiktoken\n",
    "\n",
    "\n",
    "class PDFChatbot:\n",
    "\n",
    "    def __init__(self, pdf_path, groq_api_key):\n",
    "\n",
    "        self.pdf_path = r\"C:\\Users\\amrit\\Downloads\\survey cdc.pdf\"\n",
    "\n",
    "        self.groq_api_key = \"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\"\n",
    "\n",
    "        self.history = []   \n",
    "        self.last_sources = []\n",
    "\n",
    "        self.token_limit = 3000\n",
    "\n",
    "        self.tokenizer = tiktoken.get_encoding(\n",
    "            \"cl100k_base\"\n",
    "        )\n",
    "\n",
    "        self.load_pdf()\n",
    "\n",
    "        self.create_embeddings()\n",
    "\n",
    "        self.load_llm()\n",
    "\n",
    "\n",
    "    def load_pdf(self):\n",
    "\n",
    "        loader = PyPDFLoader(self.pdf_path)\n",
    "\n",
    "        documents = loader.load()\n",
    "\n",
    "        splitter = RecursiveCharacterTextSplitter(\n",
    "            chunk_size=500,\n",
    "            chunk_overlap=50\n",
    "        )\n",
    "\n",
    "        self.chunks = splitter.split_documents(\n",
    "            documents\n",
    "        )\n",
    "\n",
    "        self.texts = [\n",
    "            doc.page_content for doc in self.chunks\n",
    "        ]\n",
    "\n",
    "        self.metadata = [\n",
    "            doc.metadata for doc in self.chunks\n",
    "        ]\n",
    "\n",
    "\n",
    "    def create_embeddings(self):\n",
    "\n",
    "        self.embedding_model = HuggingFaceEmbeddings(\n",
    "            model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
    "        )\n",
    "\n",
    "        embeddings = self.embedding_model.embed_documents(\n",
    "            self.texts\n",
    "        )\n",
    "\n",
    "        self.document_embeddings = np.array(\n",
    "            embeddings\n",
    "        )\n",
    "\n",
    "\n",
    "    def load_llm(self):\n",
    "\n",
    "        self.llm = ChatGroq(\n",
    "            groq_api_key=self.groq_api_key,\n",
    "            model_name=\"llama-3.3-70b-versatile\"\n",
    "        )\n",
    "\n",
    "\n",
    "    def retrieve(self, query, k=3):\n",
    "\n",
    "        query_embedding = self.embedding_model.embed_query(\n",
    "            query\n",
    "        )\n",
    "\n",
    "        similarity_scores = cosine_similarity(\n",
    "            [query_embedding],\n",
    "            self.document_embeddings\n",
    "        )[0]\n",
    "\n",
    "        top_indices = similarity_scores.argsort()[::-1][:k]\n",
    "\n",
    "        retrieved = []\n",
    "\n",
    "        for idx in top_indices:\n",
    "\n",
    "            retrieved.append({\n",
    "                \"text\": self.texts[idx],\n",
    "                \"metadata\": self.metadata[idx]\n",
    "            })\n",
    "\n",
    "        self.last_sources = retrieved\n",
    "\n",
    "        return retrieved\n",
    "\n",
    "\n",
    "    def count_tokens(self):\n",
    "\n",
    "        history_text = \"\"\n",
    "\n",
    "        for message in self.history:\n",
    "\n",
    "            history_text += (\n",
    "                f\"{message['role']}: \"\n",
    "                f\"{message['content']}\\n\"\n",
    "            )\n",
    "\n",
    "        tokens = self.tokenizer.encode(\n",
    "            history_text\n",
    "        )\n",
    "\n",
    "        return len(tokens)\n",
    "\n",
    "\n",
    "    def trim_history(self):\n",
    "\n",
    "        total_tokens = self.count_tokens()\n",
    "\n",
    "        print(\n",
    "            f\"\\nCurrent History Tokens: \"\n",
    "            f\"{total_tokens}\"\n",
    "        )\n",
    "\n",
    "        if total_tokens > self.token_limit:\n",
    "\n",
    "            self.history = self.history[-8:]\n",
    "\n",
    "            print(\n",
    "                \"\\nHistory exceeded 3000 tokens.\"\n",
    "            )\n",
    "\n",
    "            print(\n",
    "                \"History trimmed to last 4 exchanges.\"\n",
    "            )\n",
    "\n",
    "\n",
    "    def conversation_summary(self):\n",
    "\n",
    "        history_text = \"\"\n",
    "\n",
    "        for message in self.history:\n",
    "\n",
    "            history_text += (\n",
    "                f\"{message['role']}: \"\n",
    "                f\"{message['content']}\\n\"\n",
    "            )\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "        Summarize this conversation\n",
    "        in exactly 3 bullet points.\n",
    "\n",
    "        Conversation:\n",
    "        {history_text}\n",
    "        \"\"\"\n",
    "\n",
    "        response = self.llm.invoke(prompt)\n",
    "\n",
    "        return response.content\n",
    "\n",
    "\n",
    "    def show_sources(self):\n",
    "\n",
    "        print(\"\\nLAST RETRIEVED SOURCES\")\n",
    "\n",
    "        for i, source in enumerate(\n",
    "            self.last_sources,\n",
    "            start=1\n",
    "        ):\n",
    "\n",
    "            page = source[\"metadata\"].get(\n",
    "                \"page\",\n",
    "                \"Unknown\"\n",
    "            )\n",
    "\n",
    "            preview = source[\"text\"][:100].replace(\n",
    "                \"\\n\",\n",
    "                \" \"\n",
    "            )\n",
    "\n",
    "            print(f\"\\nSource {i}\")\n",
    "\n",
    "            print(f\"Page: {page}\")\n",
    "\n",
    "            print(f\"Preview: {preview}...\")\n",
    "\n",
    "\n",
    "    def ask(self, question):\n",
    "\n",
    "        if question.lower() == \"summary\":\n",
    "\n",
    "            summary = self.conversation_summary()\n",
    "\n",
    "            print(\"\\nSUMMARY\")\n",
    "\n",
    "            print(summary)\n",
    "\n",
    "            return summary\n",
    "\n",
    "\n",
    "        if question.lower() == \"sources\":\n",
    "\n",
    "            self.show_sources()\n",
    "\n",
    "            return \"Sources displayed.\"\n",
    "\n",
    "\n",
    "        retrieved_docs = self.retrieve(question)\n",
    "\n",
    "        context = \"\\n\".join(\n",
    "            [doc[\"text\"] for doc in retrieved_docs]\n",
    "        )\n",
    "\n",
    "        history_text = \"\"\n",
    "\n",
    "        for message in self.history:\n",
    "\n",
    "            history_text += (\n",
    "                f\"{message['role']}: \"\n",
    "                f\"{message['content']}\\n\"\n",
    "            )\n",
    "\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "        You are a helpful PDF chatbot.\n",
    "\n",
    "        Use conversation history and\n",
    "        document context to answer.\n",
    "\n",
    "        Conversation History:\n",
    "        {history_text}\n",
    "\n",
    "        Context:\n",
    "        {context}\n",
    "\n",
    "        User Question:\n",
    "        {question}\n",
    "        \"\"\"\n",
    "\n",
    "        response = self.llm.invoke(prompt)\n",
    "\n",
    "        answer = response.content\n",
    "\n",
    "\n",
    "        self.history.append({\n",
    "            \"role\": \"user\",\n",
    "            \"content\": question\n",
    "        })\n",
    "\n",
    "        self.history.append({\n",
    "            \"role\": \"assistant\",\n",
    "            \"content\": answer\n",
    "        })\n",
    "\n",
    "\n",
    "        self.trim_history()\n",
    "\n",
    "        return answer\n",
    "\n",
    "\n",
    "pdf_path = \"/Users/Aryaanil/Documents/survey cdc.pdf\"\n",
    "\n",
    "groq_api_key = \"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\"\n",
    "\n",
    "chatbot = PDFChatbot(\n",
    "    pdf_path,\n",
    "    groq_api_key\n",
    ")\n",
    "\n",
    "\n",
    "conversation = [\n",
    "\n",
    "    \"What is the main topic of the PDF?\",\n",
    "\n",
    "    \"Explain the topic simply.\",\n",
    "\n",
    "    \"summary\",\n",
    "\n",
    "    \"Which libraries are mentioned?\",\n",
    "\n",
    "    \"sources\",\n",
    "\n",
    "    \"How are those libraries used?\"\n",
    "]\n",
    "\n",
    "\n",
    "for turn, question in enumerate(\n",
    "    conversation,\n",
    "    start=1\n",
    "):\n",
    "\n",
    "    print(f\"\\nTURN {turn}\")\n",
    "\n",
    "    print(\"\\nUSER:\")\n",
    "    print(question)\n",
    "\n",
    "    response = chatbot.ask(question)\n",
    "\n",
    "    if question.lower() not in [\n",
    "        \"summary\",\n",
    "        \"sources\"\n",
    "    ]:\n",
    "\n",
    "        print(\"\\nBOT:\")\n",
    "        print(response)\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 70)\n",
    "\n",
    "\n",
    "print(\"\\nFINAL MESSAGE HISTORY\")\n",
    "\n",
    "\n",
    "for message in chatbot.history:\n",
    "\n",
    "    print(f\"\\n{message['role'].upper()}:\")\n",
    "\n",
    "    print(message[\"content\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cf291015-666f-4563-a0b9-633f9349a49e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
