{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "995c1257-2938-4dbd-8760-9b322e902ad9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "================================================================================\n",
      "STEP 1: GENERATED QUIZ QUESTIONS\n",
      "================================================================================\n",
      "Here are four beginner-friendly quiz questions about Python lists:\n",
      "\n",
      "**Question 1**\n",
      "What is the basic syntax to create a list in Python?\n",
      "\n",
      "A) `list = [ ];`\n",
      "B) `my_list = [ ];`\n",
      "C) `list = [];`\n",
      "D) `my_list = []`\n",
      "\n",
      "**Answer: B) `my_list = [ ];`**\n",
      "\n",
      "**Question 2**\n",
      "How do you access the first element of a list in Python?\n",
      "\n",
      "A) `my_list[0]`\n",
      "B) `my_list.get(0)`\n",
      "C) `my_list.first_element`\n",
      "D) `my_list[1]`\n",
      "\n",
      "**Answer: A) `my_list[0]`**\n",
      "\n",
      "**Question 3**\n",
      "How do you add an element to the end of a list in Python?\n",
      "\n",
      "A) `my_list.append(5)`\n",
      "B) `my_list = my_list + [5]`\n",
      "C) `my_list.insert(0, 5)`\n",
      "D) `my_list.index(5, len(my_list))`\n",
      "\n",
      "**Answer: A) `my_list.append(5)`**\n",
      "\n",
      "**Question 4**\n",
      "What is the purpose of the `len()` function when used with a list in Python?\n",
      "\n",
      "A) To add an element to the list\n",
      "B) To remove an element from the list\n",
      "C) To get the number of elements in the list\n",
      "D) To sort the list in ascending order\n",
      "\n",
      "**Answer: C) To get the number of elements in the list**\n",
      "\n",
      "================================================================================\n",
      "STEP 2: MODEL ANSWERS\n",
      "================================================================================\n",
      "Here are the detailed model answers for the given quiz questions:\n",
      "\n",
      "**Question 1: What is the basic syntax to create a list in Python?**\n",
      "\n",
      "Answer: B) `my_list = [ ];`\n",
      "\n",
      "\n",
      "Explanation: To create a list in Python, you need to use square brackets `[]` to define the list, and assign it to a variable using the assignment operator `=`. The variable name should be a descriptive name, which in this case is `my_list`. The syntax `my_list = [ ];` is correct because it initializes an empty list and assigns it to a variable named `my_list`. The other options are either incorrect or incomplete.\n",
      "\n",
      "\n",
      "Example Code:\n",
      "```python\n",
      "# Correct way to create a list\n",
      "my_list = []\n",
      "print(my_list)  # Output: []\n",
      "\n",
      "# Incorrect ways to create a list\n",
      "list = []  # Doesn't assign the list to a variable\n",
      "my_list =  # Missing list initialization\n",
      "list = []  # Doesn't assign to a variable named my_list\n",
      "```\n",
      "\n",
      "**Question 2: How do you access the first element of a list in Python?**\n",
      "\n",
      "Answer: A) `my_list[0]`\n",
      "\n",
      "\n",
      "Explanation: In Python, you can access a specific element in a list by using square brackets `[]` with the index of the element as the value inside the brackets. The index of the first element in a list is always `0`. Therefore, `my_list[0]` correctly accesses the first element of the list.\n",
      "\n",
      "\n",
      "Example Code:\n",
      "```python\n",
      "# Create a list\n",
      "my_list = [1, 2, 3]\n",
      "\n",
      "# Access the first element\n",
      "print(my_list[0])  # Output: 1\n",
      "\n",
      "# Incorrect ways to access the first element\n",
      "my_list.get(0)  # Returns the first element, but get() is not necessary\n",
      "my_list.first_element  # Lists don't have a first_element attribute\n",
      "my_list[1]  # Accesses the second element, not the first\n",
      "```\n",
      "\n",
      "**Question 3: How do you add an element to the end of a list in Python?**\n",
      "\n",
      "Answer: A) `my_list.append(5)`\n",
      "\n",
      "\n",
      "Explanation: The `append()` method in Python is used to add an element to the end of a list. It takes the element to be added as an argument, and modifies the original list. This is an efficient and Pythonic way to add elements to a list.\n",
      "\n",
      "\n",
      "Example Code:\n",
      "```python\n",
      "# Create a list\n",
      "my_list = [1, 2, 3]\n",
      "\n",
      "# Add an element to the end\n",
      "my_list.append(5)\n",
      "print(my_list)  # Output: [1, 2, 3, 5]\n",
      "\n",
      "# Incorrect ways to add an element\n",
      "my_list = my_list + [5]  # Creates a new list, doesn't modify the original\n",
      "my_list.insert(0, 5)  # Inserts the element at the beginning, not the end\n",
      "my_list.index(5, len(my_list))  # Returns the index of the element, doesn't add it\n",
      "```\n",
      "\n",
      "**Question 4: What is the purpose of the `len()` function when used with a list in Python?**\n",
      "\n",
      "Answer: C) To get the number of elements in the list\n",
      "\n",
      "\n",
      "Explanation: The `len()` function in Python returns the number of elements in a list. It is a built-in function that can be used with various data structures, including lists, tuples, and strings.\n",
      "\n",
      "\n",
      "Example Code:\n",
      "```python\n",
      "# Create a list\n",
      "my_list = [1, 2, 3]\n",
      "\n",
      "# Get the number of elements\n",
      "print(len(my_list))  # Output: 3\n",
      "\n",
      "# Incorrect ways to use len()\n",
      "len(my_list).append(5)  # Doesn't add an element, modifies the return value\n",
      "len(my_list).remove(5)  # Doesn't remove an element, modifies the return value\n",
      "len(my_list).sort()  # Doesn't sort the list, modifies the return value\n",
      "```\n",
      "\n",
      "================================================================================\n",
      "STEP 3: EVALUATION AND FEEDBACK\n",
      "================================================================================\n",
      "**Evaluation Result: 2/10**\n",
      "\n",
      "**Mistakes:**\n",
      "\n",
      "1. **Incorrect statement:** \"Python lists can only store numbers.\" - This is completely false. Python lists can store any type of data, including numbers, strings, booleans, lists, dictionaries, and more.\n",
      "2. **Incorrect statement:** \"Lists are immutable.\" - This is also false. In Python, lists are mutable, which means you can modify their contents after they're created.\n",
      "3. **Incorrect syntax:** \"We use curly brackets {} to create lists.\" - This is incorrect. In Python, you use square brackets `[]` to create lists, not curly brackets `{}`.\n",
      "4. **Incorrect statement:** \"Lists cannot contain duplicate values.\" - This is also false. Python lists can contain duplicate values.\n",
      "\n",
      "**Improvement Suggestions:**\n",
      "\n",
      "1. **Learn the basics:** Make sure you understand the basic syntax and data types in Python, including lists, tuples, strings, and dictionaries.\n",
      "2. **Practice, practice, practice:** Try creating lists with different data types, modifying lists, and accessing list elements to get a better understanding of how they work.\n",
      "3. **Use online resources:** There are many online resources available, including tutorials, videos, and documentation, that can help you learn Python and its data structures.\n",
      "4. **Read and understand the documentation:** Don't just copy and paste code from the internet. Read and understand the documentation for the functions and data structures you're using to ensure you're using them correctly.\n",
      "\n",
      "**Additional Tips:**\n",
      "\n",
      "* Python lists are a powerful data structure that can store any type of data.\n",
      "* Lists are mutable, which means you can modify their contents after they're created.\n",
      "* Use square brackets `[]` to create lists, not curly brackets `{}`.\n",
      "* Lists can contain duplicate values.\n",
      "\n",
      "Keep practicing, and you'll become a Python expert in no time!\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")\n",
    "\n",
    "topic = \"Python lists\"\n",
    "\n",
    "step1_prompt = f\"\"\"\n",
    "Generate 4 quiz questions about {topic}.\n",
    "Keep questions beginner-friendly.\n",
    "\"\"\"\n",
    "\n",
    "response1 = client.chat.completions.create(\n",
    "\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "\n",
    "    messages=[\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": step1_prompt\n",
    "        }\n",
    "    ],\n",
    "\n",
    "    temperature=0.7\n",
    ")\n",
    "\n",
    "quiz_questions = response1.choices[0].message.content\n",
    "\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"STEP 1: GENERATED QUIZ QUESTIONS\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(quiz_questions)\n",
    "\n",
    "step2_prompt = f\"\"\"\n",
    "Provide detailed model answers for the following quiz questions.\n",
    "\n",
    "Questions:\n",
    "{quiz_questions}\n",
    "\"\"\"\n",
    "\n",
    "response2 = client.chat.completions.create(\n",
    "\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "\n",
    "    messages=[\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": step2_prompt\n",
    "        }\n",
    "    ],\n",
    "\n",
    "    temperature=0.7\n",
    ")\n",
    "\n",
    "model_answers = response2.choices[0].message.content\n",
    "\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"STEP 2: MODEL ANSWERS\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(model_answers)\n",
    "\n",
    "student_answer = \"\"\"\n",
    "Python lists can only store numbers.\n",
    "Lists are immutable.\n",
    "We use curly brackets {} to create lists.\n",
    "Lists cannot contain duplicate values.\n",
    "\"\"\"\n",
    "\n",
    "step3_prompt = f\"\"\"\n",
    "You are an exam evaluator.\n",
    "\n",
    "Question Topic:\n",
    "{topic}\n",
    "\n",
    "Correct Model Answers:\n",
    "{model_answers}\n",
    "\n",
    "Student Answer:\n",
    "{student_answer}\n",
    "\n",
    "Evaluate the student's answer.\n",
    "\n",
    "Requirements:\n",
    "1. Give score out of 10.\n",
    "2. Mention mistakes clearly.\n",
    "3. Give improvement suggestions.\n",
    "4. Keep feedback beginner-friendly.\n",
    "\"\"\"\n",
    "\n",
    "response3 = client.chat.completions.create(\n",
    "\n",
    "    model=\"llama-3.1-8b-instant\",\n",
    "\n",
    "    messages=[\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": step3_prompt\n",
    "        }\n",
    "    ],\n",
    "\n",
    "    temperature=0.5\n",
    ")\n",
    "\n",
    "evaluation = response3.choices[0].message.content\n",
    "\n",
    "print(\"\\n\" + \"=\"*80)\n",
    "print(\"STEP 3: EVALUATION AND FEEDBACK\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(evaluation)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e007ae14-7056-4fde-9716-a2f1b446ff0d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
