{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3ea08402-8fb5-40b8-a5e3-a60ae0cbb428",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain-community in .\\anaconda3\\Lib\\site-packages (0.4.2)\n",
      "Requirement already satisfied: langchain-text-splitters in .\\anaconda3\\Lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-groq in .\\anaconda3\\Lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-huggingface in .\\anaconda3\\Lib\\site-packages (1.2.2)\n",
      "Requirement already satisfied: sentence-transformers in .\\anaconda3\\Lib\\site-packages (5.5.1)\n",
      "Requirement already satisfied: pypdf in .\\anaconda3\\Lib\\site-packages (6.12.2)\n",
      "Requirement already satisfied: scikit-learn in .\\anaconda3\\Lib\\site-packages (1.7.2)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (3.13.2)\n",
      "Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (0.4.3)\n",
      "Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (1.0.7)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (1.4.0)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (0.8.6)\n",
      "Requirement already satisfied: numpy>=2.1.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.3.5)\n",
      "Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.12.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (6.0.3)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.32.5 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.32.5)\n",
      "Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.0.43)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (8.5.0)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in .\\anaconda3\\Lib\\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.0.15)\n",
      "Requirement already satisfied: packaging>=23.2.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (24.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in .\\anaconda3\\Lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-community) (3.0.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.9.14 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)\n",
      "Requirement already satisfied: websockets>=15.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (16.0)\n",
      "Requirement already satisfied: xxhash>=3.0.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.7.0)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.24.0)\n",
      "Requirement already satisfied: anyio in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.10.0)\n",
      "Requirement already satisfied: certifi in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)\n",
      "Requirement already satisfied: idna in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in .\\anaconda3\\Lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.4.2)\n",
      "Requirement already satisfied: python-dotenv>=0.21.0 in .\\anaconda3\\Lib\\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)\n",
      "Requirement already satisfied: greenlet>=1 in .\\anaconda3\\Lib\\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.2.4)\n",
      "Requirement already satisfied: groq<1.0.0,>=0.30.0 in .\\anaconda3\\Lib\\site-packages (from langchain-groq) (0.37.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in .\\anaconda3\\Lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)\n",
      "Requirement already satisfied: sniffio in .\\anaconda3\\Lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.0)\n",
      "Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in .\\anaconda3\\Lib\\site-packages (from langchain-huggingface) (1.16.4)\n",
      "Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in .\\anaconda3\\Lib\\site-packages (from langchain-huggingface) (0.22.2)\n",
      "Requirement already satisfied: click>=8.4.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.1)\n",
      "Requirement already satisfied: filelock>=3.10.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.20.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.10.0)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.1)\n",
      "Requirement already satisfied: typer<0.26.0,>=0.20.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.20.0)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in .\\anaconda3\\Lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.4)\n",
      "Requirement already satisfied: rich>=10.11.0 in .\\anaconda3\\Lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (14.2.0)\n",
      "Requirement already satisfied: transformers<6.0.0,>=4.41.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (5.9.0)\n",
      "Requirement already satisfied: torch>=1.11.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (2.12.0)\n",
      "Requirement already satisfied: scipy>=1.0.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (1.16.3)\n",
      "Requirement already satisfied: regex>=2025.10.22 in .\\anaconda3\\Lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in .\\anaconda3\\Lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in .\\anaconda3\\Lib\\site-packages (from scikit-learn) (1.5.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in .\\anaconda3\\Lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: colorama in .\\anaconda3\\Lib\\site-packages (from click>=8.4.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.4.6)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in .\\anaconda3\\Lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\\anaconda3\\Lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.19.2)\n",
      "Requirement already satisfied: mdurl~=0.1 in .\\anaconda3\\Lib\\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.1.2)\n",
      "Requirement already satisfied: setuptools<82 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)\n",
      "Requirement already satisfied: sympy>=1.13.3 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)\n",
      "Requirement already satisfied: networkx>=2.5.1 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.5)\n",
      "Requirement already satisfied: jinja2 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\\anaconda3\\Lib\\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in .\\anaconda3\\Lib\\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "d37c1a4095fe4da59e45cada333a22ef",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "TURN 1\n",
      "\n",
      "USER:\n",
      "What is the main topic of the PDF?\n",
      "\n",
      "BOT:\n",
      "The main topic of the PDF appears to be related to academic and student-related matters, with a focus on the student community, specifically regarding stress and how students handle difficult situations.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 2\n",
      "\n",
      "USER:\n",
      "Can you explain that topic in simpler words?\n",
      "\n",
      "BOT:\n",
      "The topic is about how students feel and deal with stress. The PDF says that most students experience stress sometimes or often, but they generally feel happy in their daily lives. Only a small percentage of students said they rarely or never experience stress. Think of it like this: stress is common among students, but they usually find ways to manage it and still have a pretty good life overall.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 3\n",
      "\n",
      "USER:\n",
      "Which tools or libraries are related to it?\n",
      "\n",
      "BOT:\n",
      "The PDF appears to be related to a survey report from the SRM Institute of Science and Technology, specifically the Faculty of Science and Humanities, Department of Computer Applications. \n",
      "\n",
      "Given the context of the survey, which focuses on student happiness and emotional well-being, the tools or libraries related to it might be those used for data analysis, survey creation, or statistical processing. Some possible tools or libraries that could be related to this PDF include:\n",
      "\n",
      "1. Data analysis libraries like Pandas, NumPy, or Matplotlib (for Python)\n",
      "2. Survey creation tools like Google Forms, Microsoft Forms, or SurveyMonkey\n",
      "3. Statistical processing software like R, SPSS, or SAS\n",
      "\n",
      "However, without more specific information about the technical aspects of the survey or the PDF, it's difficult to provide a more precise answer. If you have any further questions or context, I'd be happy to try and help.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 4\n",
      "\n",
      "USER:\n",
      "How are those libraries used in the document?\n",
      "\n",
      "BOT:\n",
      "Based on the context of the PDF, which appears to be a survey report related to student happiness and emotional well-being, the libraries I mentioned earlier (Pandas, NumPy, Matplotlib, Google Forms, Microsoft Forms, SurveyMonkey, R, SPSS, or SAS) might be used in the following ways:\n",
      "\n",
      "1. **Data analysis libraries like Pandas, NumPy, or Matplotlib**: These libraries could be used to analyze the survey data, such as calculating the frequency of responses to questions like \"Do you feel comfortable sharing your thoughts and feelings with close people?\" or \"How many hours of sleep do you usually get per night?\". They might also be used to create visualizations, like bar charts or histograms, to represent the distribution of responses.\n",
      "2. **Survey creation tools like Google Forms, Microsoft Forms, or SurveyMonkey**: These tools might have been used to create and distribute the survey to the respondents. They could have been used to design the survey questions, collect responses, and store the data.\n",
      "3. **Statistical processing software like R, SPSS, or SAS**: These software packages could be used to perform statistical analyses on the survey data, such as calculating means, standard deviations, or correlations between variables. They might also be used to perform more advanced analyses, like regression or factor analysis, to identify patterns and relationships in the data.\n",
      "\n",
      "For example, the survey might have used Pandas to import and manipulate the survey data, and then used Matplotlib to create visualizations of the results. The survey might have also used Google Forms to collect the data and then exported it to a CSV file for analysis with Pandas.\n",
      "\n",
      "Here's a hypothetical example of how the libraries might be used in the document:\n",
      "\n",
      "* The survey data is collected using Google Forms and exported to a CSV file.\n",
      "* The CSV file is imported into Pandas, which is used to clean and manipulate the data.\n",
      "* Matplotlib is used to create visualizations of the data, such as a bar chart showing the frequency of responses to the question \"Do you feel comfortable sharing your thoughts and feelings with close people?\".\n",
      "* R or SPSS is used to perform statistical analyses on the data, such as calculating the correlation between the number of hours of sleep per night and the level of comfort sharing thoughts and feelings with close people.\n",
      "\n",
      "Keep in mind that this is just a hypothetical example, and the actual use of libraries in the document might be different.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "TURN 5\n",
      "\n",
      "USER:\n",
      "Summarize our conversation in a few lines.\n",
      "\n",
      "BOT:\n",
      "We discussed the main topic of the PDF, which is about student stress and happiness. I explained it in simpler words, stating that stress is common among students, but they usually find ways to manage it. We also talked about the tools and libraries related to the PDF, such as data analysis libraries and survey creation tools, and how they might be used in the document to analyze and visualize survey data.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "FULL MESSAGE HISTORY\n",
      "\n",
      "USER:\n",
      "What is the main topic of the PDF?\n",
      "\n",
      "ASSISTANT:\n",
      "The main topic of the PDF appears to be related to academic and student-related matters, with a focus on the student community, specifically regarding stress and how students handle difficult situations.\n",
      "\n",
      "USER:\n",
      "Can you explain that topic in simpler words?\n",
      "\n",
      "ASSISTANT:\n",
      "The topic is about how students feel and deal with stress. The PDF says that most students experience stress sometimes or often, but they generally feel happy in their daily lives. Only a small percentage of students said they rarely or never experience stress. Think of it like this: stress is common among students, but they usually find ways to manage it and still have a pretty good life overall.\n",
      "\n",
      "USER:\n",
      "Which tools or libraries are related to it?\n",
      "\n",
      "ASSISTANT:\n",
      "The PDF appears to be related to a survey report from the SRM Institute of Science and Technology, specifically the Faculty of Science and Humanities, Department of Computer Applications. \n",
      "\n",
      "Given the context of the survey, which focuses on student happiness and emotional well-being, the tools or libraries related to it might be those used for data analysis, survey creation, or statistical processing. Some possible tools or libraries that could be related to this PDF include:\n",
      "\n",
      "1. Data analysis libraries like Pandas, NumPy, or Matplotlib (for Python)\n",
      "2. Survey creation tools like Google Forms, Microsoft Forms, or SurveyMonkey\n",
      "3. Statistical processing software like R, SPSS, or SAS\n",
      "\n",
      "However, without more specific information about the technical aspects of the survey or the PDF, it's difficult to provide a more precise answer. If you have any further questions or context, I'd be happy to try and help.\n",
      "\n",
      "USER:\n",
      "How are those libraries used in the document?\n",
      "\n",
      "ASSISTANT:\n",
      "Based on the context of the PDF, which appears to be a survey report related to student happiness and emotional well-being, the libraries I mentioned earlier (Pandas, NumPy, Matplotlib, Google Forms, Microsoft Forms, SurveyMonkey, R, SPSS, or SAS) might be used in the following ways:\n",
      "\n",
      "1. **Data analysis libraries like Pandas, NumPy, or Matplotlib**: These libraries could be used to analyze the survey data, such as calculating the frequency of responses to questions like \"Do you feel comfortable sharing your thoughts and feelings with close people?\" or \"How many hours of sleep do you usually get per night?\". They might also be used to create visualizations, like bar charts or histograms, to represent the distribution of responses.\n",
      "2. **Survey creation tools like Google Forms, Microsoft Forms, or SurveyMonkey**: These tools might have been used to create and distribute the survey to the respondents. They could have been used to design the survey questions, collect responses, and store the data.\n",
      "3. **Statistical processing software like R, SPSS, or SAS**: These software packages could be used to perform statistical analyses on the survey data, such as calculating means, standard deviations, or correlations between variables. They might also be used to perform more advanced analyses, like regression or factor analysis, to identify patterns and relationships in the data.\n",
      "\n",
      "For example, the survey might have used Pandas to import and manipulate the survey data, and then used Matplotlib to create visualizations of the results. The survey might have also used Google Forms to collect the data and then exported it to a CSV file for analysis with Pandas.\n",
      "\n",
      "Here's a hypothetical example of how the libraries might be used in the document:\n",
      "\n",
      "* The survey data is collected using Google Forms and exported to a CSV file.\n",
      "* The CSV file is imported into Pandas, which is used to clean and manipulate the data.\n",
      "* Matplotlib is used to create visualizations of the data, such as a bar chart showing the frequency of responses to the question \"Do you feel comfortable sharing your thoughts and feelings with close people?\".\n",
      "* R or SPSS is used to perform statistical analyses on the data, such as calculating the correlation between the number of hours of sleep per night and the level of comfort sharing thoughts and feelings with close people.\n",
      "\n",
      "Keep in mind that this is just a hypothetical example, and the actual use of libraries in the document might be different.\n",
      "\n",
      "USER:\n",
      "Summarize our conversation in a few lines.\n",
      "\n",
      "ASSISTANT:\n",
      "We discussed the main topic of the PDF, which is about student stress and happiness. I explained it in simpler words, stating that stress is common among students, but they usually find ways to manage it. We also talked about the tools and libraries related to the PDF, such as data analysis libraries and survey creation tools, and how they might be used in the document to analyze and visualize survey data.\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "!{sys.executable} -m pip install \\\n",
    "langchain-community \\\n",
    "langchain-text-splitters \\\n",
    "langchain-groq \\\n",
    "langchain-huggingface \\\n",
    "sentence-transformers \\\n",
    "pypdf \\\n",
    "scikit-learn\n",
    "\n",
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "from langchain_groq import ChatGroq\n",
    "\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "class PDFChatbot:\n",
    "\n",
    "    def __init__(self, pdf_path, groq_api_key):\n",
    "\n",
    "        self.pdf_path = r\"C:\\Users\\amrit\\Downloads\\survey cdc.pdf\"\n",
    "\n",
    "        self.groq_api_key = \"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\"\n",
    "\n",
    "        self.chat_history = []\n",
    "\n",
    "        self.load_pdf()\n",
    "\n",
    "        self.create_embeddings()\n",
    "\n",
    "        self.load_llm()\n",
    "\n",
    "\n",
    "    def load_pdf(self):\n",
    "\n",
    "        loader = PyPDFLoader(self.pdf_path)\n",
    "\n",
    "        documents = loader.load()\n",
    "\n",
    "        splitter = RecursiveCharacterTextSplitter(\n",
    "            chunk_size=500,\n",
    "            chunk_overlap=50\n",
    "        )\n",
    "\n",
    "        self.chunks = splitter.split_documents(documents)\n",
    "\n",
    "        self.texts = [doc.page_content for doc in self.chunks]\n",
    "\n",
    "\n",
    "    def create_embeddings(self):\n",
    "\n",
    "        self.embedding_model = HuggingFaceEmbeddings(\n",
    "            model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
    "        )\n",
    "\n",
    "        embeddings = self.embedding_model.embed_documents(\n",
    "            self.texts\n",
    "        )\n",
    "\n",
    "        self.document_embeddings = np.array(embeddings)\n",
    "\n",
    "\n",
    "    def load_llm(self):\n",
    "\n",
    "        self.llm = ChatGroq(\n",
    "            groq_api_key=self.groq_api_key,\n",
    "            model_name=\"llama-3.3-70b-versatile\"\n",
    "        )\n",
    "\n",
    "\n",
    "    def retrieve(self, query, k=3):\n",
    "\n",
    "        query_embedding = self.embedding_model.embed_query(query)\n",
    "\n",
    "        similarity_scores = cosine_similarity(\n",
    "            [query_embedding],\n",
    "            self.document_embeddings\n",
    "        )[0]\n",
    "\n",
    "        top_indices = similarity_scores.argsort()[::-1][:k]\n",
    "\n",
    "        retrieved_chunks = [\n",
    "            self.texts[i] for i in top_indices\n",
    "        ]\n",
    "\n",
    "        return retrieved_chunks\n",
    "\n",
    "\n",
    "    def ask(self, question):\n",
    "\n",
    "        retrieved_docs = self.retrieve(question)\n",
    "\n",
    "        context = \"\\n\".join(retrieved_docs)\n",
    "\n",
    "        history_text = \"\"\n",
    "\n",
    "        for message in self.chat_history:\n",
    "\n",
    "            history_text += f\"{message['role']}: {message['content']}\\n\"\n",
    "\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "        You are a helpful PDF chatbot.\n",
    "\n",
    "        Use the conversation history and document context\n",
    "        to answer the user's question.\n",
    "\n",
    "        Conversation History:\n",
    "        {history_text}\n",
    "\n",
    "        Context:\n",
    "        {context}\n",
    "\n",
    "        User Question:\n",
    "        {question}\n",
    "        \"\"\"\n",
    "\n",
    "\n",
    "        response = self.llm.invoke(prompt)\n",
    "\n",
    "        answer = response.content\n",
    "\n",
    "\n",
    "        self.chat_history.append({\n",
    "            \"role\": \"user\",\n",
    "            \"content\": question\n",
    "        })\n",
    "\n",
    "        self.chat_history.append({\n",
    "            \"role\": \"assistant\",\n",
    "            \"content\": answer\n",
    "        })\n",
    "\n",
    "        return answer\n",
    "\n",
    "\n",
    "pdf_path = r\"C:\\Users\\amrit\\Downloads\\survey cdc.pdf\"\n",
    "\n",
    "groq_api_key = \"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\"\n",
    "\n",
    "\n",
    "chatbot = PDFChatbot(\n",
    "    pdf_path,\n",
    "    groq_api_key\n",
    ")\n",
    "\n",
    "\n",
    "questions = [\n",
    "\n",
    "    \"What is the main topic of the PDF?\",\n",
    "\n",
    "    \"Can you explain that topic in simpler words?\",\n",
    "\n",
    "    \"Which tools or libraries are related to it?\",\n",
    "\n",
    "    \"How are those libraries used in the document?\",\n",
    "\n",
    "    \"Summarize our conversation in a few lines.\"\n",
    "]\n",
    "\n",
    "\n",
    "for i, question in enumerate(questions, start=1):\n",
    "\n",
    "    answer = chatbot.ask(question)\n",
    "\n",
    "    print(f\"\\nTURN {i}\")\n",
    "\n",
    "    print(\"\\nUSER:\")\n",
    "    print(question)\n",
    "\n",
    "    print(\"\\nBOT:\")\n",
    "    print(answer)\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 70)\n",
    "\n",
    "\n",
    "print(\"\\nFULL MESSAGE HISTORY\")\n",
    "\n",
    "\n",
    "for message in chatbot.chat_history:\n",
    "\n",
    "    print(f\"\\n{message['role'].upper()}:\")\n",
    "    print(message['content'])\n",
    "#%%"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d987aa03-02d9-470f-a953-57d91a9ba53d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
