{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "bf96f4f2-11c2-4281-875d-9f83694ad3d4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain-community in .\\anaconda3\\Lib\\site-packages (0.4.2)\n",
      "Requirement already satisfied: langchain-text-splitters in .\\anaconda3\\Lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-groq in .\\anaconda3\\Lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: langchain-huggingface in .\\anaconda3\\Lib\\site-packages (1.2.2)\n",
      "Requirement already satisfied: sentence-transformers in .\\anaconda3\\Lib\\site-packages (5.5.1)\n",
      "Requirement already satisfied: pypdf in .\\anaconda3\\Lib\\site-packages (6.12.2)\n",
      "Requirement already satisfied: scikit-learn in .\\anaconda3\\Lib\\site-packages (1.7.2)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (3.13.2)\n",
      "Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (0.4.3)\n",
      "Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (1.0.7)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (1.4.0)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (0.8.6)\n",
      "Requirement already satisfied: numpy>=2.1.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.3.5)\n",
      "Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.12.0)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (6.0.3)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.32.5 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.32.5)\n",
      "Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (2.0.43)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in .\\anaconda3\\Lib\\site-packages (from langchain-community) (8.5.0)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)\n",
      "Requirement already satisfied: propcache>=0.2.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in .\\anaconda3\\Lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in .\\anaconda3\\Lib\\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.12.4)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.0.15)\n",
      "Requirement already satisfied: packaging>=23.2.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (24.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in .\\anaconda3\\Lib\\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain-community) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in .\\anaconda3\\Lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain-community) (3.0.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.9.14 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)\n",
      "Requirement already satisfied: websockets>=15.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (16.0)\n",
      "Requirement already satisfied: xxhash>=3.0.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.7.0)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in .\\anaconda3\\Lib\\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.24.0)\n",
      "Requirement already satisfied: anyio in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.10.0)\n",
      "Requirement already satisfied: certifi in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)\n",
      "Requirement already satisfied: idna in .\\anaconda3\\Lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in .\\anaconda3\\Lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in .\\anaconda3\\Lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain-community) (0.4.2)\n",
      "Requirement already satisfied: python-dotenv>=0.21.0 in .\\anaconda3\\Lib\\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in .\\anaconda3\\Lib\\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)\n",
      "Requirement already satisfied: greenlet>=1 in .\\anaconda3\\Lib\\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.2.4)\n",
      "Requirement already satisfied: groq<1.0.0,>=0.30.0 in .\\anaconda3\\Lib\\site-packages (from langchain-groq) (0.37.1)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in .\\anaconda3\\Lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)\n",
      "Requirement already satisfied: sniffio in .\\anaconda3\\Lib\\site-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.0)\n",
      "Requirement already satisfied: huggingface-hub<2.0.0,>=0.33.4 in .\\anaconda3\\Lib\\site-packages (from langchain-huggingface) (1.16.4)\n",
      "Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in .\\anaconda3\\Lib\\site-packages (from langchain-huggingface) (0.22.2)\n",
      "Requirement already satisfied: click>=8.4.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.1)\n",
      "Requirement already satisfied: filelock>=3.10.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.20.0)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.10.0)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.0)\n",
      "Requirement already satisfied: tqdm>=4.42.1 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.1)\n",
      "Requirement already satisfied: typer<0.26.0,>=0.20.0 in .\\anaconda3\\Lib\\site-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.20.0)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in .\\anaconda3\\Lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.4)\n",
      "Requirement already satisfied: rich>=10.11.0 in .\\anaconda3\\Lib\\site-packages (from typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (14.2.0)\n",
      "Requirement already satisfied: transformers<6.0.0,>=4.41.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (5.9.0)\n",
      "Requirement already satisfied: torch>=1.11.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (2.12.0)\n",
      "Requirement already satisfied: scipy>=1.0.0 in .\\anaconda3\\Lib\\site-packages (from sentence-transformers) (1.16.3)\n",
      "Requirement already satisfied: regex>=2025.10.22 in .\\anaconda3\\Lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in .\\anaconda3\\Lib\\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)\n",
      "Requirement already satisfied: joblib>=1.2.0 in .\\anaconda3\\Lib\\site-packages (from scikit-learn) (1.5.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in .\\anaconda3\\Lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: colorama in .\\anaconda3\\Lib\\site-packages (from click>=8.4.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.4.6)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in .\\anaconda3\\Lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\\anaconda3\\Lib\\site-packages (from rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2.19.2)\n",
      "Requirement already satisfied: mdurl~=0.1 in .\\anaconda3\\Lib\\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.26.0,>=0.20.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.1.2)\n",
      "Requirement already satisfied: setuptools<82 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)\n",
      "Requirement already satisfied: sympy>=1.13.3 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)\n",
      "Requirement already satisfied: networkx>=2.5.1 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.5)\n",
      "Requirement already satisfied: jinja2 in .\\anaconda3\\Lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\\anaconda3\\Lib\\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in .\\anaconda3\\Lib\\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\amrit\\AppData\\Local\\Temp\\ipykernel_8580\\747072615.py:4: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.\n",
      "  from langchain_community.document_loaders import PyPDFLoader\n",
      "Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "70cd7b35ae6548c9bc653fb905b1db5d",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "===================================\n",
      "QUESTIONS INSIDE DOCUMENT\n",
      "===================================\n",
      "\n",
      "SOURCE CHUNKS USED:\n",
      "\n",
      "Chunk 1\n",
      "Page Number: 3\n",
      "Preview: t o  a c a d e m i c  a n d  s t u d e n t -  r e l a t e d  m a t t e r s .  O v e r a l l ,  t h e\n",
      "------------------------------------------------------------\n",
      "Chunk 2\n",
      "Page Number: 6\n",
      "Preview: •  L o w e r  p e r c e n t a g e s  i n d i c a t e d  * “ R a r e l y ”  ( 9 % ) *  a n d  * “ N e\n",
      "------------------------------------------------------------\n",
      "Chunk 3\n",
      "Page Number: 7\n",
      "Preview: 3 .  H a n d l e  D i f f i c u l t  S i t u a t i o n s •  T h e  h i g h e s t  r e s p o n s e  (\n",
      "------------------------------------------------------------\n",
      "\n",
      "QUESTION:\n",
      "What is the main topic of the PDF?\n",
      "\n",
      "ANSWER:\n",
      "The main topic of the PDF is academic and student-related matters, largely centered on the student community.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "SOURCE CHUNKS USED:\n",
      "\n",
      "Chunk 1\n",
      "Page Number: 11\n",
      "Preview: S ection B: Happiness & Emotional Well-being  5. On a scale of 1–10, how happy do you feel in your d\n",
      "------------------------------------------------------------\n",
      "Chunk 2\n",
      "Page Number: 3\n",
      "Preview: t o  a c a d e m i c  a n d  s t u d e n t -  r e l a t e d  m a t t e r s .  O v e r a l l ,  t h e\n",
      "------------------------------------------------------------\n",
      "Chunk 3\n",
      "Page Number: 11\n",
      "Preview: S u r v e y  Q u e s t i o n n a i r e :  H a p p i n e s s  a n d  L i f e  S a t i s f a c t i o n\n",
      "------------------------------------------------------------\n",
      "\n",
      "QUESTION:\n",
      "Which tools or libraries are mentioned in the document?\n",
      "\n",
      "ANSWER:\n",
      "I could not find this in the document.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "SOURCE CHUNKS USED:\n",
      "\n",
      "Chunk 1\n",
      "Page Number: 3\n",
      "Preview: t o  a c a d e m i c  a n d  s t u d e n t -  r e l a t e d  m a t t e r s .  O v e r a l l ,  t h e\n",
      "------------------------------------------------------------\n",
      "Chunk 2\n",
      "Page Number: 6\n",
      "Preview: 1 .  H a v e  S o m e o n e  t o  T a l k  T o •  T h e  h i g h e s t  p e r c e n t a g e  o f  r \n",
      "------------------------------------------------------------\n",
      "Chunk 3\n",
      "Page Number: 7\n",
      "Preview: 3 .  H a n d l e  D i f f i c u l t  S i t u a t i o n s •  T h e  h i g h e s t  r e s p o n s e  (\n",
      "------------------------------------------------------------\n",
      "\n",
      "QUESTION:\n",
      "Summarize the important concepts discussed in the PDF.\n",
      "\n",
      "ANSWER:\n",
      "The PDF discusses the background status of survey respondents, specifically focusing on two concepts: \n",
      "\n",
      "1. \"Have Someone to Talk To\": The highest percentage of respondents (35%) reported \"Always\" having someone to talk to, followed by 32% who selected \"Sometimes\", and smaller percentages who chose \"Often\", \"Rarely\", and \"Never\".\n",
      "\n",
      "2. \"Handle Difficult Situations\": The highest response (44) was \"Sometimes\", with 35% reporting \"Often\", and 15% selecting \"Always\". Only a small percentage chose \"Rarely\" and \"Never\". \n",
      "\n",
      "These concepts are centered on the student community, as part of a larger survey on academic and student-related matters.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "===================================\n",
      "QUESTIONS OUTSIDE DOCUMENT\n",
      "===================================\n",
      "\n",
      "SOURCE CHUNKS USED:\n",
      "\n",
      "Chunk 1\n",
      "Page Number: 13\n",
      "Preview: S a t i s f i e d N e u t r a l D i s s a t i s f i e d V e r y  d i s s a t i s f i e d\n",
      "------------------------------------------------------------\n",
      "Chunk 2\n",
      "Page Number: 7\n",
      "Preview: T h i s  i n d i c a t e s  t h a t  m o s t  r e s p o n d e n t s  b e l i e v e  t h e y  a r e  \n",
      "------------------------------------------------------------\n",
      "Chunk 3\n",
      "Page Number: 8\n",
      "Preview: c o m m u n i c a t i o n .  A  s m a l l  p e r c e n t a g e  o f  r e s p o n d e n t s  * r a r \n",
      "------------------------------------------------------------\n",
      "\n",
      "QUESTION:\n",
      "Who won the FIFA World Cup 2022?\n",
      "\n",
      "ANSWER:\n",
      "I could not find this in the document.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "SOURCE CHUNKS USED:\n",
      "\n",
      "Chunk 1\n",
      "Page Number: 13\n",
      "Preview: S a t i s f i e d N e u t r a l D i s s a t i s f i e d V e r y  d i s s a t i s f i e d\n",
      "------------------------------------------------------------\n",
      "Chunk 2\n",
      "Page Number: 14\n",
      "Preview: ( O p e n - e n d e d  q u e s t i o n  –  W r i t e  y o u r  a n s w e r )\n",
      "------------------------------------------------------------\n",
      "Chunk 3\n",
      "Page Number: 8\n",
      "Preview: s a i d  t h e y  a l w a y s  f e e l  c o m f o r t a b l e  s h a r i n g *  t h e i r  f e e l i\n",
      "------------------------------------------------------------\n",
      "\n",
      "QUESTION:\n",
      "What is the capital of Japan?\n",
      "\n",
      "ANSWER:\n",
      "I could not find this in the document.\n",
      "\n",
      "======================================================================\n",
      "\n",
      "FULL MESSAGE HISTORY\n",
      "\n",
      "USER:\n",
      "What is the main topic of the PDF?\n",
      "\n",
      "ASSISTANT:\n",
      "The main topic of the PDF is academic and student-related matters, largely centered on the student community.\n",
      "\n",
      "USER:\n",
      "Which tools or libraries are mentioned in the document?\n",
      "\n",
      "ASSISTANT:\n",
      "I could not find this in the document.\n",
      "\n",
      "USER:\n",
      "Summarize the important concepts discussed in the PDF.\n",
      "\n",
      "ASSISTANT:\n",
      "The PDF discusses the background status of survey respondents, specifically focusing on two concepts: \n",
      "\n",
      "1. \"Have Someone to Talk To\": The highest percentage of respondents (35%) reported \"Always\" having someone to talk to, followed by 32% who selected \"Sometimes\", and smaller percentages who chose \"Often\", \"Rarely\", and \"Never\".\n",
      "\n",
      "2. \"Handle Difficult Situations\": The highest response (44) was \"Sometimes\", with 35% reporting \"Often\", and 15% selecting \"Always\". Only a small percentage chose \"Rarely\" and \"Never\". \n",
      "\n",
      "These concepts are centered on the student community, as part of a larger survey on academic and student-related matters.\n",
      "\n",
      "USER:\n",
      "Who won the FIFA World Cup 2022?\n",
      "\n",
      "ASSISTANT:\n",
      "I could not find this in the document.\n",
      "\n",
      "USER:\n",
      "What is the capital of Japan?\n",
      "\n",
      "ASSISTANT:\n",
      "I could not find this in the document.\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install \\\n",
    "langchain-community \\\n",
    "langchain-text-splitters \\\n",
    "langchain-groq \\\n",
    "langchain-huggingface \\\n",
    "sentence-transformers \\\n",
    "pypdf \\\n",
    "scikit-learn\n",
    "\n",
    "from langchain_community.document_loaders import PyPDFLoader\n",
    "\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "\n",
    "from langchain_huggingface import HuggingFaceEmbeddings\n",
    "\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "from langchain_groq import ChatGroq\n",
    "\n",
    "import numpy as np\n",
    "\n",
    "class PDFChatbot:\n",
    "\n",
    "    def __init__(self, pdf_path, groq_api_key):\n",
    "\n",
    "        self.pdf_path = pdf_path\n",
    "\n",
    "        self.groq_api_key = groq_api_key\n",
    "\n",
    "        self.chat_history = []\n",
    "\n",
    "        self.load_pdf()\n",
    "\n",
    "        self.create_embeddings()\n",
    "\n",
    "        self.load_llm()\n",
    "\n",
    "    def load_pdf(self):\n",
    "\n",
    "        loader = PyPDFLoader(self.pdf_path)\n",
    "\n",
    "        documents = loader.load()\n",
    "\n",
    "        splitter = RecursiveCharacterTextSplitter(\n",
    "            chunk_size=500,\n",
    "            chunk_overlap=50\n",
    "        )\n",
    "\n",
    "        self.chunks = splitter.split_documents(documents)\n",
    "\n",
    "    def create_embeddings(self):\n",
    "\n",
    "        self.embedding_model = HuggingFaceEmbeddings(\n",
    "            model_name=\"sentence-transformers/all-MiniLM-L6-v2\"\n",
    "        )\n",
    "\n",
    "        texts = [\n",
    "            doc.page_content\n",
    "            for doc in self.chunks\n",
    "        ]\n",
    "\n",
    "        embeddings = self.embedding_model.embed_documents(texts)\n",
    "\n",
    "        self.document_embeddings = np.array(embeddings)\n",
    "\n",
    "    def load_llm(self):\n",
    "\n",
    "        self.llm = ChatGroq(\n",
    "            groq_api_key=self.groq_api_key,\n",
    "            model_name=\"llama-3.3-70b-versatile\"\n",
    "        )\n",
    "\n",
    "    def retrieve(self, query, k=3):\n",
    "\n",
    "        query_embedding = self.embedding_model.embed_query(query)\n",
    "\n",
    "        similarity_scores = cosine_similarity(\n",
    "            [query_embedding],\n",
    "            self.document_embeddings\n",
    "        )[0]\n",
    "\n",
    "        top_indices = similarity_scores.argsort()[::-1][:k]\n",
    "\n",
    "        retrieved_docs = [\n",
    "            self.chunks[i]\n",
    "            for i in top_indices\n",
    "        ]\n",
    "\n",
    "        return retrieved_docs\n",
    "\n",
    "    def ask(self, question):\n",
    "\n",
    "        retrieved_docs = self.retrieve(question)\n",
    "\n",
    "        context = \"\\n\".join([\n",
    "            doc.page_content\n",
    "            for doc in retrieved_docs\n",
    "        ])\n",
    "\n",
    "        history_text = \"\"\n",
    "\n",
    "        for message in self.chat_history:\n",
    "\n",
    "            history_text += (\n",
    "                f\"{message['role']}: \"\n",
    "                f\"{message['content']}\\n\"\n",
    "            )\n",
    "\n",
    "\n",
    "        prompt = f\"\"\"\n",
    "        You are a strict PDF chatbot.\n",
    "\n",
    "        Answer ONLY using the provided document context.\n",
    "\n",
    "        If the answer is not present in the context,\n",
    "        reply exactly:\n",
    "\n",
    "        \"I could not find this in the document.\"\n",
    "\n",
    "        Do not guess.\n",
    "        Do not use outside knowledge.\n",
    "\n",
    "        Conversation History:\n",
    "        {history_text}\n",
    "\n",
    "        Context:\n",
    "        {context}\n",
    "\n",
    "        User Question:\n",
    "        {question}\n",
    "        \"\"\"\n",
    "\n",
    "\n",
    "        response = self.llm.invoke(prompt)\n",
    "\n",
    "        answer = response.content\n",
    "\n",
    "        self.chat_history.append({\n",
    "            \"role\": \"user\",\n",
    "            \"content\": question\n",
    "        })\n",
    "\n",
    "        self.chat_history.append({\n",
    "            \"role\": \"assistant\",\n",
    "            \"content\": answer\n",
    "        })\n",
    "\n",
    "        print(\"\\nSOURCE CHUNKS USED:\\n\")\n",
    "\n",
    "        for i, doc in enumerate(retrieved_docs, start=1):\n",
    "\n",
    "            page_number = doc.metadata.get(\n",
    "                \"page\",\n",
    "                \"Unknown\"\n",
    "            )\n",
    "\n",
    "            chunk_preview = (\n",
    "                doc.page_content[:100]\n",
    "                .replace(\"\\n\", \" \")\n",
    "            )\n",
    "\n",
    "            print(f\"Chunk {i}\")\n",
    "            print(f\"Page Number: {page_number}\")\n",
    "            print(f\"Preview: {chunk_preview}\")\n",
    "            print(\"-\" * 60)\n",
    "\n",
    "\n",
    "        return answer\n",
    "\n",
    "pdf_path = r\"C:\\Users\\amrit\\Downloads\\survey cdc.pdf\"\n",
    "\n",
    "groq_api_key = \"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\"\n",
    "\n",
    "chatbot = PDFChatbot(\n",
    "    pdf_path,\n",
    "    groq_api_key\n",
    ")\n",
    "\n",
    "in_scope_questions = [\n",
    "\n",
    "    \"What is the main topic of the PDF?\",\n",
    "\n",
    "    \"Which tools or libraries are mentioned in the document?\",\n",
    "\n",
    "    \"Summarize the important concepts discussed in the PDF.\"\n",
    "]\n",
    "\n",
    "out_scope_questions = [\n",
    "\n",
    "    \"Who won the FIFA World Cup 2022?\",\n",
    "\n",
    "    \"What is the capital of Japan?\"\n",
    "]\n",
    "\n",
    "print(\"===================================\")\n",
    "print(\"QUESTIONS INSIDE DOCUMENT\")\n",
    "print(\"===================================\")\n",
    "\n",
    "for question in in_scope_questions:\n",
    "\n",
    "    answer = chatbot.ask(question)\n",
    "\n",
    "    print(\"\\nQUESTION:\")\n",
    "    print(question)\n",
    "\n",
    "    print(\"\\nANSWER:\")\n",
    "    print(answer)\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 70)\n",
    "\n",
    "print(\"\\n===================================\")\n",
    "print(\"QUESTIONS OUTSIDE DOCUMENT\")\n",
    "print(\"===================================\")\n",
    "\n",
    "for question in out_scope_questions:\n",
    "\n",
    "    answer = chatbot.ask(question)\n",
    "\n",
    "    print(\"\\nQUESTION:\")\n",
    "    print(question)\n",
    "\n",
    "    print(\"\\nANSWER:\")\n",
    "    print(answer)\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 70)\n",
    "\n",
    "print(\"\\nFULL MESSAGE HISTORY\")\n",
    "\n",
    "for message in chatbot.chat_history:\n",
    "\n",
    "    print(f\"\\n{message['role'].upper()}:\")\n",
    "    print(message['content'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "02cd8d5e-4630-4de2-a747-d82177251e8e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
