{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a1bf9485-fcde-4ab2-bf45-4fc5f22494cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting groq\n",
      "  Downloading groq-1.2.0-py3-none-any.whl.metadata (16 kB)\n",
      "Requirement already satisfied: anyio<5,>=3.5.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from groq) (4.10.0)\n",
      "Requirement already satisfied: distro<2,>=1.7.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from groq) (1.9.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from groq) (0.28.1)\n",
      "Requirement already satisfied: pydantic<3,>=1.9.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from groq) (2.12.4)\n",
      "Requirement already satisfied: sniffio in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from groq) (1.3.0)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.14 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from groq) (4.15.0)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from anyio<5,>=3.5.0->groq) (3.11)\n",
      "Requirement already satisfied: certifi in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->groq) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->groq) (1.0.9)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3,>=1.9.0->groq) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3,>=1.9.0->groq) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)\n",
      "Downloading groq-1.2.0-py3-none-any.whl (142 kB)\n",
      "Installing collected packages: groq\n",
      "Successfully installed groq-1.2.0\n"
     ]
    }
   ],
   "source": [
    "!pip install groq"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "93fdd9ec-2d4d-4d3d-89ae-f95e1f922220",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "TEMPERATURE: 0.1\n",
      "============================================================\n",
      "**Recursion: A Real-World Example**\n",
      "\n",
      "Recursion is a programming technique where a function calls itself repeatedly until it reaches a base case that stops the recursion. This technique is useful for solving problems that have a recursive structure, such as tree traversals, factorial calculations, and more.\n",
      "\n",
      "**Example: Calculating the Total Number of Folders in a File System**\n",
      "\n",
      "Imagine you have a file system with folders and subfolders. You want to write a program that calculates the total number of folders in the file system.\n",
      "\n",
      "**Recursive Solution**\n",
      "\n",
      "Here's a recursive solution in Python:\n",
      "```python\n",
      "def count_folders(folder):\n",
      "    # Base case: if the folder is empty, return 0\n",
      "    if not folder:\n",
      "        return 0\n",
      "    \n",
      "    # Count the current folder\n",
      "    count = 1\n",
      "    \n",
      "    # Recursively count the subfolders\n",
      "    for subfolder in folder:\n",
      "        count += count_folders(subfolder)\n",
      "    \n",
      "    return count\n",
      "```\n",
      "**How it Works**\n",
      "\n",
      "1. The `count_folders` function takes a `folder` as input, which is a list of subfolders.\n",
      "2. The base case is when the `folder` is empty (`not folder`). In this case, we return 0, as there are no folders to count.\n",
      "3. If the `folder` is not empty, we count the current folder by incrementing the `count` variable by 1.\n",
      "4. We then recursively call `count_folders` on each subfolder in the `folder` list.\n",
      "5. The recursive calls return the total number of folders in each subfolder.\n",
      "6. We add the total number of folders in each subfolder to the `count` variable.\n",
      "7. Finally, we return the total count of folders.\n",
      "\n",
      "**Example Use Case**\n",
      "\n",
      "Suppose we have the following file system structure:\n",
      "```python\n",
      "root\n",
      "|-- folder1\n",
      "|    |-- subfolder1\n",
      "|    |-- subfolder2\n",
      "|-- folder2\n",
      "|    |-- subfolder3\n",
      "|    |-- subfolder4\n",
      "|-- folder3\n",
      "```\n",
      "We can call the `count_folders` function on the `root` folder like this:\n",
      "```python\n",
      "root_folders = [\n",
      "    {'name': 'folder1', 'subfolders': ['subfolder1', 'subfolder2']},\n",
      "    {'name': 'folder2', 'subfolders': ['subfolder3', 'subfolder4']},\n",
      "    {'name': 'folder3'}\n",
      "]\n",
      "\n",
      "total_folders = count_folders(root_folders)\n",
      "print(total_folders)  # Output: 7\n",
      "```\n",
      "In this example, the `count_folders` function recursively counts the total number of folders in the file system, including the subfolders.\n",
      "\n",
      "**Non-Recursive Solution**\n",
      "\n",
      "For comparison, here's a non-recursive solution using a loop:\n",
      "```python\n",
      "def count_folders(folder):\n",
      "    count = 0\n",
      "    for subfolder in folder:\n",
      "        count += 1\n",
      "        if subfolder['subfolders']:\n",
      "            count += count_folders(subfolder['subfolders'])\n",
      "    return count\n",
      "```\n",
      "While the non-recursive solution is more efficient in terms of memory usage, the recursive solution is often more intuitive and easier to understand, especially for complex problems with a recursive structure.\n",
      "\n",
      "============================================================\n",
      "TEMPERATURE: 0.7\n",
      "============================================================\n",
      "**Recursion: A Real-World Example**\n",
      "\n",
      "Recursion is a programming technique where a function calls itself repeatedly until it reaches a base case that stops the recursion. This technique can be used to solve problems that have a recursive structure, such as tree traversals, factorial calculations, and more.\n",
      "\n",
      "**Example: A Recursive Calculator for a Simple Math Problem**\n",
      "\n",
      "Let's consider a simple math problem: calculating the factorial of a number. The factorial of a number n (denoted by n!) is the product of all positive integers from 1 to n.\n",
      "\n",
      "For example, if we want to calculate 5!, we need to multiply 5 by 4 by 3 by 2 by 1.\n",
      "\n",
      "**Recursive Function:**\n",
      "\n",
      "Here's a simple recursive function in Python that calculates the factorial of a number:\n",
      "```python\n",
      "def factorial(n):\n",
      "    # Base case: if n is 0 or 1, return 1\n",
      "    if n == 0 or n == 1:\n",
      "        return 1\n",
      "    # Recursive case: call factorial(n-1) and multiply by n\n",
      "    else:\n",
      "        return n * factorial(n-1)\n",
      "```\n",
      "**How it Works:**\n",
      "\n",
      "1. The function `factorial(n)` is called with the argument `5`.\n",
      "2. Since `n` is not 0 or 1, the function calls itself with the argument `factorial(4)`.\n",
      "3. The function `factorial(4)` calls itself with the argument `factorial(3)`.\n",
      "4. The function `factorial(3)` calls itself with the argument `factorial(2)`.\n",
      "5. The function `factorial(2)` calls itself with the argument `factorial(1)`.\n",
      "6. The function `factorial(1)` returns 1 (since `n` is 1).\n",
      "7. The function `factorial(2)` returns 2 (since `n` is 2) by multiplying `n` (2) by the result of `factorial(1)`.\n",
      "8. The function `factorial(3)` returns 6 (since `n` is 3) by multiplying `n` (3) by the result of `factorial(2)`.\n",
      "9. The function `factorial(4)` returns 24 (since `n` is 4) by multiplying `n` (4) by the result of `factorial(3)`.\n",
      "10. The function `factorial(5)` returns 120 (since `n` is 5) by multiplying `n` (5) by the result of `factorial(4)`.\n",
      "\n",
      "**Base Case:**\n",
      "\n",
      "The base case is `n == 0 or n == 1`, which stops the recursion. When `n` reaches 0 or 1, the function returns 1, and the recursion unwinds.\n",
      "\n",
      "**Advantages of Recursion:**\n",
      "\n",
      "Recursion can be a powerful technique for solving problems that have a recursive structure. It can also be a elegant way to write code that is easy to understand and maintain.\n",
      "\n",
      "However, recursion can also lead to stack overflows if the recursion is too deep, so it's essential to use recursion judiciously and with caution.\n",
      "\n",
      "**Example Use Case:**\n",
      "\n",
      "Recursion can be used to solve a wide range of problems, including:\n",
      "\n",
      "* Tree traversals (e.g., calculating the height of a tree)\n",
      "* Graph traversals (e.g., finding the shortest path between two nodes)\n",
      "* Dynamic programming (e.g., calculating the Fibonacci sequence)\n",
      "* File system traversal (e.g., finding all files in a directory)\n",
      "\n",
      "In conclusion, recursion is a powerful technique for solving problems that have a recursive structure. By using a recursive function, we can write elegant and efficient code that is easy to understand and maintain.\n",
      "\n",
      "============================================================\n",
      "TEMPERATURE: 1.5\n",
      "============================================================\n",
      "**Recursion: A Powerful Programming Concept**\n",
      "\n",
      "Recursion is a fundamental concept in computer programming where a function calls itself repeatedly until it reaches a base case that stops the recursion. In this explanation, we'll use a real-world example to illustrate how recursion works.\n",
      "\n",
      "**Example: Calculating the Sum of Natural Numbers**\n",
      "\n",
      "Suppose we want to calculate the sum of the first few natural numbers: 1 + 2 + 3 + 4 + ... + n.\n",
      "\n",
      "**Recursive Formula:**\n",
      "The sum of the first n natural numbers can be calculated using the formula: `S(1) + S(n-1)`, where `S(1)` is the sum of the first number (which is 1), and `S(n-1)` is the sum of the remaining numbers `(2 + 3 + ... + n)`.\n",
      "\n",
      "Here is a pseudo-code representation of the recursive function:\n",
      "```python\n",
      "def sum_of_natural_numbers(n):\n",
      "  // Base Case: If n is 1, return 1\n",
      "  if n == 1:\n",
      "    return 1\n",
      "    \n",
      "  // Recursive Case: \n",
      "  // Add 1 (n's first number) + the sum of (n-1)\n",
      "  return 1 + sum_of_natural_numbers(n-1)\n",
      "```\n",
      "**Explanation:**\n",
      "The function calls itself (`sum_of_natural_numbers(n-1)`), calculating the sum of the subsequent numbers. This continues until `n` reaches 1, at which point the function stops its recursive call (`base case`). At each level of recursion, the `n-th` number is added to the result from the previous level.\n",
      "\n",
      "**Example Walkthrough:**\n",
      "\n",
      "| Level of Recursion | Calculation | Result |\n",
      "| ------------------ | ------- | ------- |\n",
      "| Level 1:         | sum of_n(n-1: 3) = ?               \t1 + sum_of_n(3)    \t4\n",
      " sum_of_natural\\_number  | = 4                  + 4       = 8\n",
      "\n",
      "|Level\\_(2\\):    | Sum Of n-1 (2)=?\n",
      "\n",
      "    |\n",
      "|Level\\_(3\\)|    sUM\\_natural \\ \\ (1):?\n",
      "\n",
      "    1 |\n",
      "\n",
      "Recursion is an essential programming technique for complex problems like the Fibonacci sequence or the Tree-Traversal algorithm (used in database searches).\n"
     ]
    }
   ],
   "source": [
    "from groq import Groq\n",
    "\n",
    "client = Groq(\n",
    "    api_key=\"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\"\n",
    ")\n",
    "\n",
    "question = \"Explain recursion with a real-world example\"\n",
    "\n",
    "temperatures = [0.1, 0.7, 1.5]\n",
    "\n",
    "for temp in temperatures:\n",
    "\n",
    "    print(\"\\n\" + \"=\"*60)\n",
    "    print(f\"TEMPERATURE: {temp}\")\n",
    "    print(\"=\"*60)\n",
    "\n",
    "    response = client.chat.completions.create(\n",
    "        model=\"llama-3.1-8b-instant\",\n",
    "        messages=[\n",
    "            {\n",
    "                \"role\": \"user\",\n",
    "                \"content\": question\n",
    "            }\n",
    "        ],\n",
    "        temperature=temp\n",
    "    )\n",
    "\n",
    "    answer = response.choices[0].message.content\n",
    "\n",
    "    print(answer)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0ff2f69-c8d8-442b-bc64-fb0df36687ad",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
