{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "a528e69f-b0d3-4b88-b9a4-cfcce4e588c2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain-text-splitters in c:\\users\\amrit\\anaconda3\\lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: pandas in c:\\users\\amrit\\anaconda3\\lib\\site-packages (2.3.3)\n",
      "Requirement already satisfied: langchain-core<2.0.0,>=1.2.31 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-text-splitters) (1.4.0)\n",
      "Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.33)\n",
      "Requirement already satisfied: langchain-protocol>=0.0.14 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.0.15)\n",
      "Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.8.5)\n",
      "Requirement already satisfied: packaging>=23.2.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (25.0)\n",
      "Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.12.4)\n",
      "Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (6.0.3)\n",
      "Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (9.1.2)\n",
      "Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.15.0)\n",
      "Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.16.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.0.0)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.28.1)\n",
      "Requirement already satisfied: orjson>=3.9.14 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.11.9)\n",
      "Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.0.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.32.5)\n",
      "Requirement already satisfied: xxhash>=3.0.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.7.0)\n",
      "Requirement already satisfied: zstandard>=0.23.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.24.0)\n",
      "Requirement already satisfied: anyio in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (4.10.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2026.4.22)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.0.9)\n",
      "Requirement already satisfied: idna in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.11)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.16.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.41.5)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (0.4.2)\n",
      "Requirement already satisfied: numpy>=1.26.0 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pandas) (2.3.5)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (3.4.4)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (2.5.0)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\amrit\\anaconda3\\lib\\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-text-splitters) (1.3.0)\n",
      "\n",
      "============================================================\n",
      "Chunk Size: 200\n",
      "============================================================\n",
      "Total Chunks: 18\n",
      "\n",
      "Chunk Character Counts:\n",
      "\n",
      "    Chunk Number  Character Count\n",
      "0              1              198\n",
      "1              2               45\n",
      "2              3              195\n",
      "3              4               87\n",
      "4              5              197\n",
      "5              6               52\n",
      "6              7              195\n",
      "7              8               40\n",
      "8              9              188\n",
      "9             10               49\n",
      "10            11              188\n",
      "11            12               64\n",
      "12            13              198\n",
      "13            14               51\n",
      "14            15              195\n",
      "15            16              196\n",
      "16            17              199\n",
      "17            18               62\n",
      "\n",
      "Sample Chunks:\n",
      "\n",
      "Chunk 1:\n",
      "\n",
      "Artificial Intelligence is transforming industries across the world. It helps automate repetitive tasks and improve efficiency in businesses. AI systems can analyze large amounts of data quickly and\n",
      "------------------------------------------------------------\n",
      "Chunk 2:\n",
      "\n",
      "large amounts of data quickly and accurately.\n",
      "------------------------------------------------------------\n",
      "Chunk 3:\n",
      "\n",
      "Machine Learning is a branch of AI that enables systems to learn from data. Instead of being explicitly programmed, models improve their performance through experience. Popular algorithms include\n",
      "------------------------------------------------------------\n",
      "\n",
      "============================================================\n",
      "Chunk Size: 500\n",
      "============================================================\n",
      "Total Chunks: 5\n",
      "\n",
      "Chunk Character Counts:\n",
      "\n",
      "   Chunk Number  Character Count\n",
      "0             1              456\n",
      "1             2              424\n",
      "2             3              420\n",
      "3             4              413\n",
      "4             5              422\n",
      "\n",
      "Sample Chunks:\n",
      "\n",
      "Chunk 1:\n",
      "\n",
      "Artificial Intelligence is transforming industries across the world. It helps automate repetitive tasks and improve efficiency in businesses. AI systems can analyze large amounts of data quickly and accurately.\n",
      "\n",
      "Machine Learning is a branch of AI that enables systems to learn from data. Instead of being explicitly programmed, models improve their performance through experience. Popular algorithms include regression, decision trees, and neural networks.\n",
      "------------------------------------------------------------\n",
      "Chunk 2:\n",
      "\n",
      "Deep Learning is a subset of machine learning based on neural networks. It is widely used in image recognition, natural language processing, and speech recognition. Large datasets and powerful GPUs are often required.\n",
      "\n",
      "Python is one of the most popular programming languages for AI and data science. Libraries such as NumPy, Pandas, Matplotlib, and Scikit-learn simplify development. Python syntax is also beginner friendly.\n",
      "------------------------------------------------------------\n",
      "Chunk 3:\n",
      "\n",
      "Data preprocessing is an important step in machine learning projects. Missing values, duplicate rows, and inconsistent formats must be handled carefully. Clean data improves model accuracy significantly.\n",
      "\n",
      "Natural Language Processing allows computers to understand human language. Applications include chatbots, translation systems, and sentiment analysis. NLP models are improving rapidly with transformer architectures.\n",
      "------------------------------------------------------------\n",
      "\n",
      "============================================================\n",
      "Chunk Size: 1000\n",
      "============================================================\n",
      "Total Chunks: 3\n",
      "\n",
      "Chunk Character Counts:\n",
      "\n",
      "   Chunk Number  Character Count\n",
      "0             1              882\n",
      "1             2              835\n",
      "2             3              422\n",
      "\n",
      "Sample Chunks:\n",
      "\n",
      "Chunk 1:\n",
      "\n",
      "Artificial Intelligence is transforming industries across the world. It helps automate repetitive tasks and improve efficiency in businesses. AI systems can analyze large amounts of data quickly and accurately.\n",
      "\n",
      "Machine Learning is a branch of AI that enables systems to learn from data. Instead of being explicitly programmed, models improve their performance through experience. Popular algorithms include regression, decision trees, and neural networks.\n",
      "\n",
      "Deep Learning is a subset of machine learning based on neural networks. It is widely used in image recognition, natural language processing, and speech recognition. Large datasets and powerful GPUs are often required.\n",
      "\n",
      "Python is one of the most popular programming languages for AI and data science. Libraries such as NumPy, Pandas, Matplotlib, and Scikit-learn simplify development. Python syntax is also beginner friendly.\n",
      "------------------------------------------------------------\n",
      "Chunk 2:\n",
      "\n",
      "Data preprocessing is an important step in machine learning projects. Missing values, duplicate rows, and inconsistent formats must be handled carefully. Clean data improves model accuracy significantly.\n",
      "\n",
      "Natural Language Processing allows computers to understand human language. Applications include chatbots, translation systems, and sentiment analysis. NLP models are improving rapidly with transformer architectures.\n",
      "\n",
      "Computer Vision focuses on enabling machines to interpret visual data. Facial recognition, object detection, and autonomous vehicles use computer vision techniques. Convolutional neural networks are commonly applied.\n",
      "\n",
      "Cloud computing provides scalable resources for AI applications. Services like AWS, Azure, and Google Cloud support model training and deployment. This reduces infrastructure costs for companies.\n",
      "------------------------------------------------------------\n",
      "Chunk 3:\n",
      "\n",
      "Cybersecurity is becoming more important as digital systems expand. AI can help detect fraud, malware, and unusual network behavior. However, attackers also use AI techniques for advanced threats.\n",
      "\n",
      "The future of AI includes advancements in robotics, healthcare, education, and automation. Ethical considerations such as privacy, fairness, and transparency are essential. Responsible AI development is a major global focus.\n",
      "------------------------------------------------------------\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import pandas as pd\n",
    "\n",
    "!{sys.executable} -m pip install langchain-text-splitters pandas\n",
    "\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "\n",
    "text = \"\"\"\n",
    "Artificial Intelligence is transforming industries across the world. It helps automate repetitive tasks and improve efficiency in businesses. AI systems can analyze large amounts of data quickly and accurately.\n",
    "\n",
    "Machine Learning is a branch of AI that enables systems to learn from data. Instead of being explicitly programmed, models improve their performance through experience. Popular algorithms include regression, decision trees, and neural networks.\n",
    "\n",
    "Deep Learning is a subset of machine learning based on neural networks. It is widely used in image recognition, natural language processing, and speech recognition. Large datasets and powerful GPUs are often required.\n",
    "\n",
    "Python is one of the most popular programming languages for AI and data science. Libraries such as NumPy, Pandas, Matplotlib, and Scikit-learn simplify development. Python syntax is also beginner friendly.\n",
    "\n",
    "Data preprocessing is an important step in machine learning projects. Missing values, duplicate rows, and inconsistent formats must be handled carefully. Clean data improves model accuracy significantly.\n",
    "\n",
    "Natural Language Processing allows computers to understand human language. Applications include chatbots, translation systems, and sentiment analysis. NLP models are improving rapidly with transformer architectures.\n",
    "\n",
    "Computer Vision focuses on enabling machines to interpret visual data. Facial recognition, object detection, and autonomous vehicles use computer vision techniques. Convolutional neural networks are commonly applied.\n",
    "\n",
    "Cloud computing provides scalable resources for AI applications. Services like AWS, Azure, and Google Cloud support model training and deployment. This reduces infrastructure costs for companies.\n",
    "\n",
    "Cybersecurity is becoming more important as digital systems expand. AI can help detect fraud, malware, and unusual network behavior. However, attackers also use AI techniques for advanced threats.\n",
    "\n",
    "The future of AI includes advancements in robotics, healthcare, education, and automation. Ethical considerations such as privacy, fairness, and transparency are essential. Responsible AI development is a major global focus.\n",
    "\"\"\"\n",
    "\n",
    "with open(\"sample.txt\", \"w\") as file:\n",
    "    file.write(text)\n",
    "\n",
    "with open(\"sample.txt\", \"r\") as file:\n",
    "    content = file.read()\n",
    "\n",
    "chunk_sizes = [200, 500, 1000]\n",
    "\n",
    "for size in chunk_sizes:\n",
    "\n",
    "    print(f\"\\n{'='*60}\")\n",
    "    print(f\"Chunk Size: {size}\")\n",
    "    print(f\"{'='*60}\")\n",
    "\n",
    "    splitter = RecursiveCharacterTextSplitter(\n",
    "        chunk_size=size,\n",
    "        chunk_overlap=40\n",
    "    )\n",
    "\n",
    "    chunks = splitter.split_text(content)\n",
    "\n",
    "    print(\"Total Chunks:\", len(chunks))\n",
    "\n",
    "    chunk_data = []\n",
    "\n",
    "    for i, chunk in enumerate(chunks):\n",
    "        chunk_data.append({\n",
    "            \"Chunk Number\": i + 1,\n",
    "            \"Character Count\": len(chunk)\n",
    "        })\n",
    "\n",
    "    df = pd.DataFrame(chunk_data)\n",
    "\n",
    "    print(\"\\nChunk Character Counts:\\n\")\n",
    "    print(df)\n",
    "\n",
    "    print(\"\\nSample Chunks:\\n\")\n",
    "\n",
    "    for i in range(min(3, len(chunks))):\n",
    "        print(f\"Chunk {i+1}:\\n\")\n",
    "        print(chunks[i])\n",
    "        print(\"-\" * 60)\n",
    "#%%"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f2a0917f-e483-4bbe-a657-200f075f39d9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
